'use client';
import {useState} from 'react';
import {ArrowRight,GraduationCap,Headphones,BookOpen,CheckCircle2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Progress} from '@/components/ui/progress';
import {toast} from 'sonner';
import {AudioButton,Recorder} from './study-tools';
import {sendAction,StudyState} from '@/lib/study-state';
const questions=[
{kind:'listening',fr:'Bonjour, je voudrais réserver une table pour trois personnes, samedi à dix-neuf heures trente.',q:'预订是几点？',options:['19:00','19:30','20:30'],answer:1,why:'dix-neuf heures trente 表示 19:30。'},
{kind:'reading',fr:'La bibliothèque est ouverte du mardi au samedi, de 9 h à 18 h. Elle est fermée le dimanche et le lundi.',q:'哪一天图书馆开放？',options:['星期一','星期日','星期三'],answer:2,why:'周二到周六开放，所以星期三可以去。'},
{kind:'listening',fr:'Le train pour Bordeaux est annulé. Les voyageurs peuvent prendre le prochain train à quatorze heures sans acheter un nouveau billet.',q:'旅客需要怎么做？',options:['重新买票','14:00 乘下一班，不必买新票','去另一个车站'],answer:1,why:'sans acheter un nouveau billet 表示不必购买新票。'},
{kind:'reading',fr:'Quand j’habitais à Lyon, j’allais au travail à vélo. Un jour, il a commencé à pleuvoir, alors j’ai pris le bus.',q:'那个人为什么在某一天改坐公交？',options:['自行车坏了','搬家了','开始下雨了'],answer:2,why:'下雨是那一天改变交通方式的原因，alors 引出结果。'},
{kind:'listening',fr:'J’aimerais venir à ta fête, mais je travaille jusqu’à vingt heures. Si vous êtes encore au restaurant après, je vous rejoindrai.',q:'说话人表达了什么意图？',options:['一定不去聚会','下班后，如果大家还在餐厅就去会合','要求聚会取消'],answer:1,why:'这是一项有条件的计划，而不是无条件的拒绝或承诺。'},
{kind:'reading',fr:'Les cours en ligne sont pratiques parce qu’ils permettent de gagner du temps. Pourtant, certains étudiants préfèrent la classe pour échanger directement avec leur professeur.',q:'pourtant 在这里起什么作用？',options:['提出与前面不同的考虑','总结相同的观点','说明上课地点'],answer:0,why:'pourtant 引出转折：线上方便，但有些人更重视当面交流。'}
];
export default function Assessment({state,refresh,back,openCourses}:{state:StudyState;refresh:()=>Promise<void>;back:()=>void;openCourses:()=>void}){
const [step,setStep]=useState(-1),[answers,setAnswers]=useState<(number|null)[]>(Array(6).fill(null)),[oral,setOral]=useState(0),[writing,setWriting]=useState(0),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[saved,setSaved]=useState(false),[showText,setShowText]=useState(false);
const listening=questions.reduce((s,q,i)=>s+Number(q.kind==='listening'&&answers[i]===q.answer),0),reading=questions.reduce((s,q,i)=>s+Number(q.kind==='reading'&&answers[i]===q.answer),0);
async function finish(){if(!state.user){setDone(true);return}setBusy(true);try{await sendAction('assessment',{listening,reading,oral,writing});await refresh();setSaved(true);setDone(true)}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
if(done)return <section className="panel assessment-result"><GraduationCap size={40}/><h1>这是你的学习起点。</h1><p className="muted">这次小测主要检查 A2–B1 听读基础，不能评定 C1、C2 等级。</p><div className="result-grid"><div><Headphones/><strong>{listening}<small> / 3</small></strong><span>听力样题</span></div><div><BookOpen/><strong>{reading}<small> / 3</small></strong><span>阅读样题</span></div></div><div className="grammar-note"><h3>{listening+reading>=5?'建议尝试 A2+ 过渡课程':listening+reading>=3?'建议从 A2 课程开始，逐步提高难度':'可以先从 A1 入门课程巩固基础'}</h3><p>{listening<reading?'本次听力样题更有挑战。可以先逐句听，再听整段对话。':reading<listening?'本次阅读样题更有挑战。建议多练时间顺序和连接词。':'可以保持听读输入，同时增加口语和写作输出。'}</p><p>口语自评：{oral?['','需要较多提示','能说清主要信息','能补充细节和理由'][oral]:'未评估'} · 写作自评：{writing?['','需要较多提示','能写清主要信息','能补充细节和理由'][writing]:'未评估'}</p></div><p className="muted text-small">{saved?'结果已保存到学习档案。':'试学结果仅在当前页面显示。'}</p><Button className="primary-button" onClick={openCourses}>选择适合的课程 <ArrowRight size={17}/></Button></section>;
if(step===-1)return <section className="panel assessment-intro"><span className="icon-block blue"><GraduationCap size={32}/></span><div className="eyebrow">TROUVER SON POINT DE DÉPART</div><h1>先认识一下，你现在的法语。</h1><p>6 道 A2–B1 听读小题，再做一次口语和写作自查。约 5–8 分钟。</p><div className="intro-details"><span><Headphones/>3 道听力</span><span><BookOpen/>3 道阅读</span><span><CheckCircle2/>2 项自评</span></div><p className="muted">不必查词，也不必追求全对。本小测不是正式等级测评；更高等级请根据课程目标自行选择。</p><div className="row centered"><Button className="primary-button" onClick={()=>setStep(0)}>开始小测 <ArrowRight size={17}/></Button><Button variant="ghost" onClick={back}>稍后再测</Button></div></section>;
const q=questions[step];
return <div className="assessment-page"><div className="mini-heading"><h1>水平小测</h1><span className="muted">{step<6?step+1+' / 6':'口语与写作自查'}</span></div><Progress value={Math.min(step+1,7)/7*100}/><section className="panel question-panel">{step<6?<><span className="small-tag">{q.kind==='listening'?'听一听':'读一读'}</span>{q.kind==='listening'?<div className="assessment-audio"><AudioButton text={q.fr} label="播放听力"/><Button variant="ghost" onClick={()=>setShowText(s=>!s)}>{showText?'收起原文':'需要原文辅助'}</Button>{showText&&<p lang="fr">{q.fr}</p>}</div>:<p className="reading-passage" lang="fr">{q.fr}</p>}<h2>{q.q}</h2><RadioGroup value={answers[step]===null?'':String(answers[step])} onValueChange={v=>setAnswers(a=>a.map((x,i)=>i===step?Number(v):x))}>{q.options.map((o,i)=><label className="quiz-option" htmlFor={'assess-'+step+'-'+i} key={o}><RadioGroupItem id={'assess-'+step+'-'+i} value={String(i)}/>{o}</label>)}</RadioGroup><Button disabled={answers[step]===null} className="primary-button" onClick={()=>{setStep(s=>s+1);setShowText(false)}}>下一步 <ArrowRight size={17}/></Button></>:<><h2>用自己的语言，完成一次小表达</h2><p className="writing-prompt">口语：说说你上个周末做了什么，并解释你是否喜欢这次经历。可以录音回听。</p><Recorder/><label className="field-label">你的口语自评</label><RadioGroup value={String(oral)} onValueChange={v=>setOral(Number(v))} className="self-rating">{['暂不评估','需要较多提示','能说清主要信息','能补充细节和理由'].map((label,i)=><label className="quiz-option" key={label}><RadioGroupItem value={String(i)}/>{label}</label>)}</RadioGroup><p className="writing-prompt">写作：给朋友写一条消息，邀请对方周末见面，说明时间、地点和活动。</p><Textarea value={draft} onChange={e=>setDraft(e.target.value)} maxLength={3000} aria-label="小测写作练习" placeholder="Salut…"/><label className="field-label">你的写作自评</label><RadioGroup value={String(writing)} onValueChange={v=>setWriting(Number(v))} className="self-rating">{['暂不评估','需要较多提示','能写清主要信息','能补充细节和理由'].map((label,i)=><label className="quiz-option" key={label}><RadioGroupItem value={String(i)}/>{label}</label>)}</RadioGroup><p className="muted text-small">自评结果可以保存；这段练习文字与录音仅供当前页面自查。</p><Button disabled={busy} className="primary-button" onClick={finish}>{busy?'正在保存…':'查看学习建议'} <ArrowRight size={17}/></Button></>}</section></div>
}

