'use client';
import {useEffect,useRef,useState} from 'react';
import {Volume2,Square,Mic,RotateCcw,Send,Lightbulb,Check,BookmarkPlus,ArrowRight,Eye,EyeOff,Headphones,BookOpen,PenLine,MessageCircle,CheckCircle2,Flag} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Switch} from '@/components/ui/switch';
import {Checkbox} from '@/components/ui/checkbox';
import {Textarea} from '@/components/ui/textarea';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {toast} from 'sonner';
import {Lesson} from '@/lib/curriculum';
import {levelGuide,countLearningUnits} from '@/lib/levels';
import {languageGuide,examGuide} from '@/lib/languages';
import {sendAction,StudyState} from '@/lib/study-state';

export function AudioButton({text,label='朗读',slow=false,className='',lang='fr-FR'}:{text:string;label?:string;slow?:boolean;className?:string;lang?:string}){
 const [playing,setPlaying]=useState(false);const utter=useRef<SpeechSynthesisUtterance|null>(null);
 useEffect(()=>()=>{if(utter.current){utter.current.onend=null;utter.current.onerror=null;if(typeof speechSynthesis!=='undefined')speechSynthesis.cancel()}},[]);
 function play(){if(!('speechSynthesis'in window)){toast.error('此浏览器不支持朗读，请使用支持语音的浏览器。');return}if(playing){speechSynthesis.cancel();setPlaying(false);return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=slow?.76:.94;const voice=speechSynthesis.getVoices().find(v=>v.lang.toLowerCase().startsWith(lang.slice(0,2).toLowerCase()));if(voice)u.voice=voice;u.onstart=()=>setPlaying(true);u.onend=()=>setPlaying(false);u.onerror=e=>{setPlaying(false);if(e.error!=='interrupted'&&e.error!=='canceled')toast.error('目标语言语音暂时无法播放，请检查设备的语音设置。')};utter.current=u;speechSynthesis.speak(u)}
 return <Button variant="outline" onClick={play} className={'audio-button '+className} aria-label={playing?'停止朗读':label}>{playing?<Square size={17}/>:<Volume2 size={17}/>}<span>{playing?'停止':label}</span></Button>
}
export function Recorder(){
 const [recording,setRecording]=useState(false),[url,setUrl]=useState(''),[busy,setBusy]=useState(false);const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),blobUrl=useRef('');const alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;recorder.current?.state==='recording'&&recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(blobUrl.current)URL.revokeObjectURL(blobUrl.current)}},[]);
 async function toggle(){if(recording){recorder.current?.stop();setRecording(false);return}if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){toast.error('此浏览器不支持录音，你也可以直接朗读并完成自查。');return}setBusy(true);try{const s=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){s.getTracks().forEach(t=>t.stop());return}stream.current=s;const r=new MediaRecorder(s);recorder.current=r;const chunks:BlobPart[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};r.onstop=()=>{s.getTracks().forEach(t=>t.stop());if(!alive.current)return;if(blobUrl.current)URL.revokeObjectURL(blobUrl.current);blobUrl.current=URL.createObjectURL(new Blob(chunks,{type:r.mimeType||'audio/webm'}));setUrl(blobUrl.current);setRecording(false)};r.start();setRecording(true)}catch{toast.error('未能使用麦克风。请允许录音权限，或直接进行口头练习。')}finally{setBusy(false)}}
 return <div className="recorder"><div className="row"><Button variant={recording?'destructive':'outline'} disabled={busy} onClick={toggle}>{recording?<Square size={17}/>:<Mic size={17}/>} {busy?'正在打开麦克风…':recording?'结束录音':'录一段目标语言'}</Button><span className="muted text-small">{recording?'正在录音…':'录音仅用于当前页面回听'}</span></div>{url&&<audio controls src={url} className="recorded-audio" aria-label="回听我的录音"/>}</div>
}
export function Quiz({question,options,answer,why,value,onChange,name}:{question:string;options:string[];answer:number;why:string;value:number|null;onChange:(i:number)=>void;name:string}){
 return <div className="quiz"><h3>{question}</h3><RadioGroup value={value===null?'':String(value)} onValueChange={v=>onChange(Number(v))} aria-label={question}>{options.map((o,i)=><label className={'quiz-option '+(value===i?(i===answer?'correct':'incorrect'):'')} key={o} htmlFor={name+i}><RadioGroupItem value={String(i)} id={name+i}/><span>{o}</span>{value===i&&i===answer&&<Check size={18}/>}</label>)}</RadioGroup>{value!==null&&<div className={'feedback '+(value===answer?'success':'notice')} role="status"><strong>{value===answer?'很好，理解正确。':'再看一看这个细节。'}</strong><p>{why}</p></div>}</div>
}
export function GuidedDialogue({lesson,onComplete}:{lesson:Lesson;onComplete?:()=>void}){
 const meta=languageGuide(lesson.language),learner=lesson.learnerSpeaker??'Vous';const prompts=lesson.dialogue.map((d,i)=>({...d,reply:lesson.dialogue.slice(i+1).find(next=>next.speaker===learner)?.fr||lesson.grammar.example})).filter(d=>d.speaker!==learner);const [turn,setTurn]=useState(0),[messages,setMessages]=useState<{role:string;text:string}[]>([]),[text,setText]=useState(''),[hint,setHint]=useState(false);
 const complete=turn>=prompts.length;const current=prompts[turn];
 function send(){if(text.trim().length<3){toast('试着用'+meta.practiceName+'写一句完整的回答。');return}setMessages(m=>[...m,{role:'partner',text:current.fr},{role:'you',text:text.trim()}]);setText('');setHint(false);setTurn(t=>t+1);if(turn+1>=prompts.length)onComplete?.()}
 return <div className="dialogue-practice"><div className="mini-heading"><span className="small-tag">引导式情景对话</span><span className="muted text-small">{Math.min(turn+1,prompts.length)} / {prompts.length} 轮</span></div><p className="muted">你的任务：{lesson.goal}</p><div className="chat-thread">{messages.map((m,i)=><div className={'chat-bubble '+m.role} key={i}><small>{m.role==='you'?'你':'对话伙伴'}</small><p lang={lesson.language??'fr'}>{m.text}</p></div>)}{!complete&&<div className="chat-bubble partner"><small>{current.speaker}</small><p lang={lesson.language??'fr'}>{current.fr}</p><AudioButton text={current.fr} lang={meta.locale} label="听这一句"/></div>}</div>{complete?<div className="feedback success"><strong>你完成了这段对话。</strong><p>返回参考对话，检查自己的意思是否表达清楚，再录一次试试。</p><Button variant="ghost" onClick={()=>{setTurn(0);setMessages([])}}><RotateCcw size={16}/>重新练习</Button></div>:<><form className="chat-input" onSubmit={e=>{e.preventDefault();send()}}><Input value={text} onChange={e=>setText(e.target.value)} placeholder={'用'+meta.practiceName+'回应…'} aria-label={'我的'+meta.practiceName+'回答'} maxLength={1000}/><Button type="submit" aria-label="发送回答"><Send size={18}/></Button></form><Button variant="ghost" onClick={()=>setHint(h=>!h)}><Lightbulb size={16}/>{hint?'收起提示':'给我一点提示'}</Button>{hint&&<div className="hint" lang={lesson.language??'fr'}>{current?.reply||lesson.grammar.example}</div>}</>}</div>
}
export function ReadingTask({lesson}:{lesson:Lesson}){
 const [show,setShow]=useState(false);
 if(!lesson.readingTask)return null;
 return <div className="reading-focus"><h3>进一步读懂</h3><p>{lesson.readingTask.prompt}</p><Button variant="ghost" onClick={()=>setShow(!show)}>{show?'收起分析':'思考后，查看分析'}</Button>{show&&<p className="feedback notice">{lesson.readingTask.answer}</p>}</div>;
}
export function WritingCheck({text,lesson}:{text:string;lesson:Lesson}){
 const [show,setShow]=useState(false),[checked,setChecked]=useState<number[]>([]);const language=lesson.language??'fr',words=countLearningUnits(text,language),guide=levelGuide(lesson.level),unit=language==='ja'?'字':'词';
 const connector=language==='en'?/\b(and|but|because|then|although|however|therefore|nevertheless)\b/i:language==='de'?/\b(und|aber|weil|danach|obwohl|jedoch|deshalb|dennoch)\b/i:language==='ja'?/(そして|それから|しかし|ため|ので|一方|したがって|にもかかわらず)/:/\b(et|mais|parce que|ensuite|donc|pourtant|cependant|toutefois|néanmoins)\b/i;
 const checks=[{ok:words>=guide.minWords,label:'本课建议 '+guide.minWords+'–'+guide.maxWords+' '+unit+'；请按任务补足内容。'},{ok:/[.!?…。！？]$/.test(text.trim()),label:'检查句末标点，让每句话完整。'},...(language==='ja'?[]:[{ok:/^[A-ZÀÂÇÉÈÊËÎÏÔÙÛÜŸÄÖ]/.test(text.trim()),label:'以大写字母开始句子。'}]),...(lesson.level==='A1'||lesson.level==='N4'?[]:[{ok:connector.test(text),label:'检查连接词是否准确表达转折、因果或递进。'}])];
 const issue=language==='fr'&&/\bje suis aller\b/i.test(text)?'“je suis aller” 要使用过去分词：je suis allé（男性）或 je suis allée（女性）。':language==='fr'&&/\bje va\b/i.test(text)?'“je va” 的变位需要调整：je vais。':language==='en'&&/\bI has\b/i.test(text)?'主语 I 后使用 have：I have。':language==='de'&&/\bweil\s+\w+\s+(?:ist|hat|kann)\s+\w+/i.test(text)?'weil 从句中的变位动词通常放在句末，请检查语序。':null;
 return <div className="writing-check"><div className="mini-heading"><h3>写作自查</h3><span className="muted text-small">结构提示 · 不作等级评分</span></div>{checks.map(c=><div className={'check-line '+(c.ok?'passed':'')} key={c.label}>{c.ok?<CheckCircle2 size={17}/>:<span className="empty-check"/>}<span>{c.label}</span></div>)}{words>guide.maxWords&&<p className="muted text-small">已超过建议词数。可以检查重复表达，尝试精简。</p>}{lesson.writing.checklist&&<div className="writing-reflection"><p>逐项自查后勾选：</p>{lesson.writing.checklist.map((label,i)=><label className="checkbox-line" key={label}><Checkbox checked={checked.includes(i)} onCheckedChange={v=>setChecked(items=>v===true?[...items.filter(n=>n!==i),i]:items.filter(n=>n!==i))}/><span>{label}</span></label>)}</div>}{issue&&<div className="feedback notice">{issue}</div>}<Button variant="ghost" onClick={()=>setShow(!show)}><BookOpen size={16}/>{show?'收起参考表达':'完成自己的版本后，看参考表达'}</Button>{show&&<p className="reference-text" lang={lesson.language??'fr'}>{lesson.writing.example}</p>}</div>;
}
export function LessonPlayer({lesson,bilingual,state,refresh,back,onNext,signInHref}:{lesson:Lesson;bilingual:boolean;state:StudyState;refresh:()=>Promise<void>;back:()=>void;onNext:()=>void;signInHref:string}){
 const [step,setStep]=useState(0),[listenAnswer,setListenAnswer]=useState<number|null>(null),[grammarAnswer,setGrammarAnswer]=useState<number|null>(null),[translation,setTranslation]=useState(bilingual),[transcript,setTranscript]=useState(false),[slow,setSlow]=useState(false),[spoken,setSpoken]=useState(false),[writing,setWriting]=useState(state.drafts.find(d=>d.lesson_id===lesson.id)?.body||''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[saved,setSaved]=useState(false),[reportOpen,setReportOpen]=useState(false),[report,setReport]=useState('');const seconds=useRef(0);const attempt=useRef('');const draftTouched=useRef(false),meta=languageGuide(lesson.language),learner=lesson.learnerSpeaker??'Vous';const steps=['听一听','读懂对话','词句工具','开口说','写一写'];const wordCount=countLearningUnits(writing,lesson.language);const guide=levelGuide(lesson.level);
 useEffect(()=>{const timer=window.setTimeout(()=>setTranslation(bilingual),0);return()=>window.clearTimeout(timer)},[bilingual,lesson.id]);
 useEffect(()=>{attempt.current=crypto.randomUUID();const timer=setInterval(()=>{if(document.visibilityState==='visible')seconds.current++},1000);return()=>{clearInterval(timer);if('speechSynthesis'in window)speechSynthesis.cancel()}},[lesson.id]);
 async function bookmark(wordId:string){if(!state.user){toast('登录后可以收藏词句。');return}try{await sendAction('bookmark',{wordId});await refresh();toast.success('已加入我的复习')}catch(e){toast.error((e as Error).message)}}
 async function finish(){if(wordCount<guide.completionWords){toast(`请至少写 ${guide.completionWords} 个${meta.practiceName}${meta.unit}，再完成课程。`);return}if(!state.user){setDone(true);setSaved(false);return}setBusy(true);try{await sendAction('complete',{lessonId:lesson.id,answers:[listenAnswer,grammarAnswer],writing,seconds:Math.min(seconds.current,7200),attemptId:attempt.current});setDone(true);setSaved(true);await refresh()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function saveDraft(){setBusy(true);try{await sendAction('draft',{lessonId:lesson.id,writing});toast.success('草稿已保存')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{if(!draftTouched.current){const savedDraft=state.drafts.find(d=>d.lesson_id===lesson.id);if(savedDraft)setWriting(savedDraft.body)}},[state.drafts,lesson.id]);
 const canContinue=step===0?listenAnswer!==null:step===2?grammarAnswer!==null:step===3?spoken:true;
 if(done)return <div className="lesson-complete panel"><span className="completion-icon"><CheckCircle2 size={42}/></span><div className="eyebrow">UN PAS DE PLUS</div><h1>Bien joué ! 你又前进了一步。</h1><p>你完成了「{lesson.title}」。理解与语法练习答对 {Number(listenAnswer===lesson.quiz.answer)+Number(grammarAnswer===lesson.grammar.answer)} / 2 题。</p><div className="complete-goal"><Check size={19}/>{lesson.goal}</div><p className="muted">{saved?'本课进度和写作已保存，3 个词句已加入复习。':'这次是试学。登录后可保存后续课程和复习记录。'}</p><div className="row centered">{!saved&&<Button asChild><a href={signInHref} target="_top">登录以保存后续学习</a></Button>}<Button className="primary-button" onClick={onNext}>学习下一课 <ArrowRight size={17}/></Button><Button variant="outline" onClick={back}>返回课程</Button></div></div>;
 return <div className="lesson-page"><div className="lesson-heading"><Button variant="ghost" onClick={back}>← 返回课程</Button><Button variant="ghost" onClick={()=>setReportOpen(true)}><Flag size={15}/>内容纠错</Button></div><div className="lesson-title"><div className="row"><span className="small-tag">{lesson.level} · {lesson.minutes} 分钟</span><span className="muted text-small">{examGuide(lesson.language??'fr',lesson.level).label}</span></div><h1>{lesson.title}</h1><p lang={lesson.language??'fr'}>{lesson.fr}</p><span className="muted">{lesson.goal}</span></div><div className="lesson-steps" aria-label="课程步骤">{steps.map((s,i)=><div key={s} className={i===step?'active':i<step?'finished':''}><span>{i<step?<Check size={14}/>:i+1}</span>{s}</div>)}</div><Progress value={(step+1)/5*100} className="lesson-progress"/><section className="lesson-surface panel">
 {step===0&&<><div className="mini-heading"><h2><Headphones size={22}/>先听，抓住关键信息</h2><div className="row"><Switch checked={slow} onCheckedChange={setSlow} id="slow"/><label htmlFor="slow">慢速</label></div></div><p className="muted">听一段本课对话，留意信息、语气与说话人的意图。可以反复听，也可以按需查看原文。</p><div className="audio-stage"><div className="audio-wave" aria-hidden="true">{[10,22,34,18,45,26,38,56,32,44,24,50,36,26,42,18,30,46,22,12].map((h,i)=><i key={i} style={{height:h}}/>)}</div><AudioButton text={lesson.dialogue.map(d=>d.fr).join(' ')} lang={meta.locale} label="播放本课对话" slow={slow}/><small>{meta.label} · 设备语音朗读</small></div><Button variant="ghost" onClick={()=>setTranscript(t=>!t)}>{transcript?<EyeOff size={16}/>:<Eye size={16}/>} {transcript?'收起原文':'查看'+meta.practiceName+'原文'}</Button>{transcript&&<div className="transcript" lang={lesson.language??'fr'}>{lesson.dialogue.map((d,i)=><p key={i}><strong>{d.speaker}：</strong>{d.fr}</p>)}</div>}<Quiz {...lesson.quiz} value={listenAnswer} onChange={setListenAnswer} name={lesson.id+'listen'}/></>}
 {step===1&&<><div className="mini-heading"><h2><BookOpen size={22}/>读懂每一次来回</h2><div className="row"><Switch checked={translation} onCheckedChange={setTranslation} id="translation"/><label htmlFor="translation">中文释义</label></div></div><div className="reading-dialogue">{lesson.dialogue.map((d,i)=>{const isLearner=d.speaker===learner;return <div className="dialogue-line" key={i}><span className={'speaker-avatar '+(isLearner?'you':'')}>{isLearner?'你':d.speaker.slice(0,1)}</span><div><small>{d.speaker}</small><p lang={lesson.language??'fr'}>{d.fr}</p>{translation&&<p className="translation">{d.zh}</p>}</div><AudioButton text={d.fr} label="朗读" lang={meta.locale}/></div>})}</div><div className="reading-takeaway"><Lightbulb size={20}/><div><strong>读完，再用自己的话说一遍。</strong><p>{guide.reading}</p></div></div><ReadingTask key={lesson.id} lesson={lesson}/></>}
 {step===2&&<><div className="mini-heading"><h2><BookmarkPlus size={22}/>把表达带走</h2><span className="muted text-small">词汇连同语境一起记</span></div><div className="word-list">{lesson.words.map(w=><div className="word-row" key={w.id}><div><strong lang={lesson.language??'fr'}>{w.fr}</strong><small>{w.pos} · {w.zh}</small></div><AudioButton text={w.fr} label="朗读" lang={meta.locale}/><Button variant="ghost" onClick={()=>bookmark(w.id)} aria-label={'收藏 '+w.fr}>{state.reviews.some(r=>r.word_id===w.id)?<Check size={18}/>:<BookmarkPlus size={18}/>}</Button></div>)}</div><div className="grammar-note"><span className="eyebrow">{lesson.language==='ja'?'文法ポイント':'PETITE GRAMMAIRE'}</span><h3>{lesson.grammar.title}</h3><p>{lesson.grammar.explanation}</p><blockquote lang={lesson.language??'fr'}>{lesson.grammar.example}</blockquote><span>{lesson.grammar.translation}</span></div><Quiz {...lesson.grammar} value={grammarAnswer} onChange={setGrammarAnswer} name={lesson.id+'grammar'}/></>}
 {step===3&&<><div className="mini-heading"><h2><MessageCircle size={22}/>轮到你开口了</h2></div><GuidedDialogue lesson={lesson} onComplete={()=>setSpoken(true)}/><div className="speaking-task"><h3>把你的回答大声说出来</h3><p className="muted">{guide.speaking}</p><Recorder/><label className="checkbox-line"><Checkbox checked={spoken} onCheckedChange={v=>setSpoken(v===true)}/><span>我已完成口头练习，并检查自己的意思是否清楚。</span></label></div></>}
 {step===4&&<><div className="mini-heading"><h2><PenLine size={22}/>用一段文字，把今天串起来</h2></div><p className="writing-prompt">{lesson.writing.prompt}</p><Textarea value={writing} onChange={e=>{draftTouched.current=true;setWriting(e.target.value)}} placeholder={'试着写 '+guide.minWords+'–'+guide.maxWords+' '+meta.unit+'。'} aria-label={'本课'+meta.practiceName+'写作'} className="writing-area" maxLength={6000}/><div className="mini-heading"><span className="muted text-small">{wordCount} {meta.unit} · 至少 {guide.completionWords} {meta.unit}可完成</span><Button variant="ghost" disabled={busy} onClick={saveDraft}>保存草稿</Button></div><WritingCheck text={writing} lesson={lesson}/></>}
 </section><div className="lesson-controls"><Button variant="outline" disabled={step===0} onClick={()=>setStep(s=>s-1)}>上一步</Button><span className="muted text-small">{step+1} / 5</span>{step<4?<Button className="primary-button" disabled={!canContinue} onClick={()=>{setStep(s=>s+1);window.scrollTo({top:0,behavior:'smooth'})}}>继续 <ArrowRight size={17}/></Button>:<Button className="primary-button" disabled={busy||wordCount<guide.completionWords} onClick={finish}>{busy?'正在保存…':'完成本课'} <Check size={17}/></Button>}</div><Dialog open={reportOpen} onOpenChange={setReportOpen}><DialogContent><DialogHeader><DialogTitle>反馈课程内容</DialogTitle><DialogDescription>请说明「{lesson.title}」中需要改进的句子或解释。提交后将保存给课程维护者。</DialogDescription></DialogHeader><Textarea value={report} onChange={e=>setReport(e.target.value)} placeholder="请具体描述问题…" maxLength={1000} aria-label="内容纠错说明"/><DialogFooter><Button disabled={busy||report.trim().length<5} onClick={async()=>{setBusy(true);try{await sendAction('report',{lessonId:lesson.id,body:report});setReportOpen(false);setReport('');toast.success('反馈已保存，谢谢你的帮助')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}}>提交反馈</Button></DialogFooter></DialogContent></Dialog></div>
}
