import type {Lesson} from './curriculum';
import type {LearningLevel} from './levels';

type Scenario={
  key:string;topic:string;titleZh:string;titleFr:string;placeFr:string;placeZh:string;
  partner:string;requestFr:string;requestZh:string;detailFr:string;detailZh:string;
  issueFr:string;issueZh:string;solutionFr:string;solutionZh:string;
  words:[[string,string,string],[string,string,string],[string,string,string]];
};

const scenarios:Scenario[]=[
  {key:'poste',topic:'daily',titleZh:'在邮局寄包裹',titleFr:'Envoyer un colis',placeFr:'au bureau de poste',placeZh:'邮局',partner:'Employé',requestFr:'envoyer un colis à Marseille',requestZh:'寄一个包裹到马赛',detailFr:'une livraison avant vendredi',detailZh:'周五前送达',issueFr:'le tarif rapide est plus élevé',issueZh:'快速服务价格更高',solutionFr:'comparer les deux tarifs avant de choisir',solutionZh:'选择前比较两种价格',words:[['un colis','n. m.','包裹'],['un tarif','n. m.','价格；资费'],['une livraison','n. f.','递送']]},
  {key:'pharmacie',topic:'daily',titleZh:'在药店说明需要',titleFr:'Demander conseil à la pharmacie',placeFr:'à la pharmacie',placeZh:'药店',partner:'Pharmacienne',requestFr:'demander un produit pour un rhume léger',requestZh:'咨询轻微感冒用的产品',detailFr:'un produit qui ne provoque pas de somnolence',detailZh:'不会引起困倦的产品',issueFr:'certains produits ne conviennent pas à tout le monde',issueZh:'有些产品并不适合所有人',solutionFr:'lire la notice et demander confirmation au pharmacien',solutionZh:'阅读说明并向药剂师确认',words:[['un rhume','n. m.','感冒'],['une notice','n. f.','说明书'],['la somnolence','n. f.','困倦']]},
  {key:'rendezvous',topic:'daily',titleZh:'修改预约时间',titleFr:'Déplacer un rendez-vous',placeFr:'au cabinet',placeZh:'诊所',partner:'Secrétaire',requestFr:'déplacer un rendez-vous prévu mardi',requestZh:'改动原定周二的预约',detailFr:'un créneau jeudi après-midi',detailZh:'周四下午的时段',issueFr:'les créneaux disponibles sont limités',issueZh:'可选时段有限',solutionFr:'confirmer le nouvel horaire par message',solutionZh:'通过消息确认新时间',words:[['un rendez-vous','n. m.','预约'],['un créneau','n. m.','时间段'],['déplacer','v.','改期；移动']]},
  {key:'objet-perdu',topic:'daily',titleZh:'寻找遗失物品',titleFr:'Retrouver un objet perdu',placeFr:'à l’accueil',placeZh:'服务台',partner:'Agent',requestFr:'signaler un sac oublié',requestZh:'报告一个遗忘的包',detailFr:'un sac bleu avec un carnet rouge',detailZh:'一个装着红色笔记本的蓝色包',issueFr:'plusieurs objets similaires ont été trouvés',issueZh:'找到了几件相似物品',solutionFr:'décrire précisément le contenu avant de le récupérer',solutionZh:'领取前准确描述内容',words:[['un objet perdu','n. m.','失物'],['signaler','v.','报告'],['récupérer','v.','取回']]},
  {key:'forfait',topic:'daily',titleZh:'选择手机套餐',titleFr:'Choisir un forfait mobile',placeFr:'dans une boutique de téléphonie',placeZh:'手机营业厅',partner:'Conseiller',requestFr:'choisir un forfait adapté',requestZh:'选择合适的手机套餐',detailFr:'des appels en Europe et peu de données mobiles',detailZh:'欧洲通话和少量移动数据',issueFr:'l’offre la moins chère comporte un engagement',issueZh:'最便宜的方案附带合约期',solutionFr:'comparer le prix total et la durée du contrat',solutionZh:'比较总价与合同期限',words:[['un forfait','n. m.','套餐'],['un engagement','n. m.','合约期；承诺'],['les données mobiles','n. f. pl.','移动数据']]},
  {key:'bibliotheque',topic:'daily',titleZh:'办理图书馆借阅',titleFr:'S’inscrire à la bibliothèque',placeFr:'à la bibliothèque',placeZh:'图书馆',partner:'Bibliothécaire',requestFr:'obtenir une carte de bibliothèque',requestZh:'办理图书馆借阅卡',detailFr:'emprunter des livres et accéder aux ressources numériques',detailZh:'借书并使用数字资源',issueFr:'un justificatif de domicile est demandé',issueZh:'需要住址证明',solutionFr:'présenter le document puis activer le compte en ligne',solutionZh:'提交文件并激活在线账户',words:[['emprunter','v.','借阅'],['un justificatif','n. m.','证明文件'],['une ressource','n. f.','资源']]},
  {key:'marche',topic:'food',titleZh:'在市场挑选食材',titleFr:'Faire ses courses au marché',placeFr:'au marché',placeZh:'市场',partner:'Marchand',requestFr:'acheter des légumes de saison',requestZh:'购买当季蔬菜',detailFr:'de quoi préparer un dîner pour quatre personnes',detailZh:'准备四人晚餐所需的食材',issueFr:'certains produits sont vendus en grande quantité',issueZh:'有些商品按较大份量出售',solutionFr:'adapter les quantités et demander des conseils de conservation',solutionZh:'调整份量并询问保存建议',words:[['de saison','loc. adj.','当季的'],['une quantité','n. f.','数量'],['conserver','v.','保存']]},
  {key:'allergie',topic:'food',titleZh:'说明食物过敏',titleFr:'Signaler une allergie au restaurant',placeFr:'au restaurant',placeZh:'餐厅',partner:'Serveur',requestFr:'commander un plat sans fruits à coque',requestZh:'点一份不含坚果的菜',detailFr:'vérifier les ingrédients et la préparation',detailZh:'确认原料和制作方式',issueFr:'la même cuisine prépare plusieurs plats',issueZh:'同一厨房制作多种菜品',solutionFr:'demander au serveur de vérifier le risque de contact',solutionZh:'请服务员确认接触风险',words:[['une allergie','n. f.','过敏'],['un ingrédient','n. m.','原料'],['un contact','n. m.','接触']]},
  {key:'remboursement',topic:'food',titleZh:'为有问题的商品申请处理',titleFr:'Signaler un produit défectueux',placeFr:'au service clientèle',placeZh:'客服处',partner:'Conseillère',requestFr:'signaler un appareil qui ne fonctionne pas',requestZh:'报告一件无法正常工作的商品',detailFr:'obtenir une réparation ou un échange',detailZh:'获得维修或换货',issueFr:'le reçu original est difficile à retrouver',issueZh:'原始收据不容易找到',solutionFr:'présenter la preuve numérique d’achat et examiner les options',solutionZh:'出示电子购买证明并查看可选方案',words:[['défectueux','adj.','有缺陷的'],['un échange','n. m.','换货'],['une preuve d’achat','n. f.','购买证明']]},
  {key:'recette',topic:'food',titleZh:'一起调整菜谱',titleFr:'Adapter une recette',placeFr:'dans la cuisine',placeZh:'厨房',partner:'Ami',requestFr:'adapter une recette pour six personnes',requestZh:'把食谱调整为六人份',detailFr:'réduire le sucre sans perdre la texture',detailZh:'减少糖分但保持口感',issueFr:'les proportions changent selon les ingrédients',issueZh:'比例会随原料而变化',solutionFr:'modifier une quantité à la fois et noter le résultat',solutionZh:'每次只调整一个用量并记录结果',words:[['une recette','n. f.','食谱'],['une proportion','n. f.','比例'],['la texture','n. f.','质地；口感']]},
  {key:'cantine',topic:'food',titleZh:'讨论食堂菜单',titleFr:'Améliorer le menu de la cantine',placeFr:'à la cantine',placeZh:'食堂',partner:'Responsable',requestFr:'proposer davantage de choix végétariens',requestZh:'建议增加素食选择',detailFr:'un menu abordable et varié',detailZh:'价格合适且多样的菜单',issueFr:'la cuisine doit respecter un budget fixe',issueZh:'厨房必须遵守固定预算',solutionFr:'tester un plat hebdomadaire et recueillir les avis',solutionZh:'每周试行一道菜并收集意见',words:[['végétarien','adj.','素食的'],['abordable','adj.','负担得起的'],['recueillir','v.','收集']]},
  {key:'gaspillage',topic:'food',titleZh:'减少家庭食物浪费',titleFr:'Réduire le gaspillage alimentaire',placeFr:'à la maison',placeZh:'家中',partner:'Colocataire',requestFr:'mieux organiser les repas de la semaine',requestZh:'更好地安排一周用餐',detailFr:'utiliser d’abord les produits les plus fragiles',detailZh:'先使用最容易变质的食物',issueFr:'les emplois du temps changent souvent',issueZh:'日程经常变化',solutionFr:'prévoir quelques repas flexibles et vérifier le réfrigérateur',solutionZh:'安排几顿可调整的饭并检查冰箱',words:[['le gaspillage','n. m.','浪费'],['périssable','adj.','易腐的'],['un reste','n. m.','剩余食物']]},
  {key:'train',topic:'travel',titleZh:'处理火车晚点',titleFr:'Faire face à un retard de train',placeFr:'à la gare',placeZh:'火车站',partner:'Agent',requestFr:'trouver une correspondance après un retard',requestZh:'列车晚点后寻找换乘方案',detailFr:'arriver avant une réunion importante',detailZh:'在重要会议前到达',issueFr:'la correspondance habituelle est déjà partie',issueZh:'原定接续列车已经开走',solutionFr:'comparer le prochain train et un itinéraire alternatif',solutionZh:'比较下一班车与替代路线',words:[['un retard','n. m.','延误'],['une correspondance','n. f.','换乘'],['un itinéraire','n. m.','路线']]},
  {key:'hotel',topic:'travel',titleZh:'协商酒店房间问题',titleFr:'Résoudre un problème à l’hôtel',placeFr:'à la réception de l’hôtel',placeZh:'酒店前台',partner:'Réceptionniste',requestFr:'signaler une chambre trop bruyante',requestZh:'反映房间过于吵闹',detailFr:'pouvoir dormir avant un départ matinal',detailZh:'在清晨出发前能够休息',issueFr:'aucune autre chambre n’est libre ce soir',issueZh:'今晚没有其他空房',solutionFr:'prévoir un changement demain et une solution pour cette nuit',solutionZh:'安排明天换房并解决今晚的问题',words:[['bruyant','adj.','吵闹的'],['disponible','adj.','可用的'],['une compensation','n. f.','补偿']]},
  {key:'aeroport',topic:'travel',titleZh:'确认机场行李安排',titleFr:'Gérer un bagage à l’aéroport',placeFr:'à l’aéroport',placeZh:'机场',partner:'Agente',requestFr:'enregistrer un bagage spécial',requestZh:'托运一件特殊行李',detailFr:'connaître les dimensions et les frais',detailZh:'了解尺寸要求和费用',issueFr:'les règles varient selon le billet',issueZh:'规定因机票类型而异',solutionFr:'vérifier la réservation et obtenir une confirmation écrite',solutionZh:'核对预订并取得书面确认',words:[['un bagage','n. m.','行李'],['enregistrer','v.','办理托运'],['des frais','n. m. pl.','费用']]},
  {key:'velo',topic:'travel',titleZh:'租一辆城市自行车',titleFr:'Louer un vélo en ville',placeFr:'dans une agence de location',placeZh:'租车点',partner:'Loueur',requestFr:'louer un vélo pour la journée',requestZh:'租一辆自行车一天',detailFr:'un casque et un itinéraire sûr',detailZh:'一个头盔和安全路线',issueFr:'la météo risque de changer',issueZh:'天气可能变化',solutionFr:'choisir une formule modifiable et vérifier l’équipement',solutionZh:'选择可调整的方案并检查装备',words:[['louer','v.','租用'],['un casque','n. m.','头盔'],['modifiable','adj.','可更改的']]},
  {key:'musee',topic:'travel',titleZh:'安排博物馆参观',titleFr:'Organiser une visite au musée',placeFr:'au musée',placeZh:'博物馆',partner:'Guide',requestFr:'préparer une visite en petit groupe',requestZh:'安排小组参观',detailFr:'voir l’exposition principale sans courir',detailZh:'从容观看主要展览',issueFr:'le temps disponible est limité',issueZh:'可用时间有限',solutionFr:'choisir trois œuvres et garder un temps de discussion',solutionZh:'选择三件作品并留出讨论时间',words:[['une exposition','n. f.','展览'],['une œuvre','n. f.','作品'],['un parcours','n. m.','参观路线']]},
  {key:'assurance',topic:'travel',titleZh:'读懂旅行保险条件',titleFr:'Comprendre une assurance voyage',placeFr:'dans une agence',placeZh:'服务机构',partner:'Conseiller',requestFr:'comprendre les garanties d’une assurance voyage',requestZh:'了解旅行保险保障内容',detailFr:'savoir quels imprévus sont réellement couverts',detailZh:'了解哪些意外真正受保',issueFr:'les exclusions sont présentées séparément',issueZh:'除外条款被分开列出',solutionFr:'relier chaque garantie à ses conditions et exclusions',solutionZh:'把每项保障与条件及除外条款对应起来',words:[['une garantie','n. f.','保障'],['une exclusion','n. f.','除外条款'],['être couvert','expression','受保障']]},
  {key:'plombier',topic:'home',titleZh:'预约住房维修',titleFr:'Organiser une réparation',placeFr:'dans l’appartement',placeZh:'公寓',partner:'Propriétaire',requestFr:'faire réparer une fuite',requestZh:'维修漏水问题',detailFr:'éviter des dégâts supplémentaires',detailZh:'避免进一步损坏',issueFr:'l’artisan n’est disponible que pendant les heures de travail',issueZh:'维修人员只在工作时间有空',solutionFr:'convenir d’un créneau et préciser l’accès au logement',solutionZh:'约定时间并说明如何进入住宅',words:[['une fuite','n. f.','漏水'],['un artisan','n. m.','维修技工'],['un dégât','n. m.','损坏']]},
  {key:'internet',topic:'home',titleZh:'解决家庭网络故障',titleFr:'Résoudre une panne d’internet',placeFr:'à domicile',placeZh:'家中',partner:'Technicienne',requestFr:'rétablir une connexion internet',requestZh:'恢复网络连接',detailFr:'pouvoir travailler depuis la maison',detailZh:'能够居家工作',issueFr:'la panne peut venir de plusieurs équipements',issueZh:'故障可能来自多个设备',solutionFr:'tester chaque élément puis planifier une intervention',solutionZh:'逐项测试并安排上门处理',words:[['une panne','n. f.','故障'],['une connexion','n. f.','连接'],['une intervention','n. f.','上门处理；干预']]},
  {key:'demenagement',topic:'home',titleZh:'计划搬家',titleFr:'Préparer un déménagement',placeFr:'dans le nouvel appartement',placeZh:'新公寓',partner:'Ami',requestFr:'organiser un déménagement sans oublier les démarches',requestZh:'安排搬家并完成各项手续',detailFr:'répartir les cartons et les changements d’adresse',detailZh:'分配装箱和地址变更任务',issueFr:'les personnes disponibles ne le sont pas le même jour',issueZh:'可以帮忙的人时间不同',solutionFr:'établir un calendrier et attribuer des tâches précises',solutionZh:'制定日程并分配具体任务',words:[['un déménagement','n. m.','搬家'],['un carton','n. m.','纸箱'],['une démarche','n. f.','手续']]},
  {key:'energie',topic:'home',titleZh:'降低住房能耗',titleFr:'Réduire la consommation d’énergie',placeFr:'dans l’immeuble',placeZh:'楼房',partner:'Voisine',requestFr:'réduire la consommation d’énergie',requestZh:'降低能源消耗',detailFr:'agir sans diminuer fortement le confort',detailZh:'采取行动而不过度降低舒适度',issueFr:'les travaux coûteux ne sont pas possibles immédiatement',issueZh:'昂贵改造无法立刻进行',solutionFr:'mesurer les usages et commencer par des changements simples',solutionZh:'测量使用情况并从简单改变开始',words:[['la consommation','n. f.','消耗量'],['isoler','v.','隔热'],['un usage','n. m.','使用方式']]},
  {key:'bruit',topic:'home',titleZh:'处理邻里噪音',titleFr:'Parler d’un problème de bruit',placeFr:'dans l’immeuble',placeZh:'公寓楼',partner:'Voisin',requestFr:'parler d’un bruit répété le soir',requestZh:'讨论晚间反复出现的噪音',detailFr:'trouver une règle acceptable pour chacun',detailZh:'找到双方都能接受的规则',issueFr:'les horaires de travail sont différents',issueZh:'双方工作时间不同',solutionFr:'fixer une plage calme et prévoir les exceptions',solutionZh:'确定安静时段并约定例外情况',words:[['une nuisance sonore','n. f.','噪音干扰'],['une plage horaire','n. f.','时段'],['une exception','n. f.','例外']]},
  {key:'colocation',topic:'home',titleZh:'确定合租规则',titleFr:'Définir des règles de colocation',placeFr:'dans l’appartement partagé',placeZh:'合租公寓',partner:'Colocataire',requestFr:'répartir les espaces et les tâches',requestZh:'分配空间与家务',detailFr:'préserver des habitudes différentes',detailZh:'兼顾不同生活习惯',issueFr:'la même règle n’a pas le même coût pour chacun',issueZh:'同一规则对每个人的负担不同',solutionFr:'tester une répartition puis la réexaminer ensemble',solutionZh:'试行一种分配方式并共同复盘',words:[['une colocation','n. f.','合租'],['répartir','v.','分配'],['réexaminer','v.','重新审视']]},
  {key:'inscription',topic:'work',titleZh:'选择一门培训课程',titleFr:'Choisir une formation',placeFr:'au centre de formation',placeZh:'培训中心',partner:'Conseillère',requestFr:'choisir une formation compatible avec son emploi du temps',requestZh:'选择与日程相符的培训',detailFr:'progresser à l’oral et obtenir un suivi',detailZh:'提高口语并获得跟进指导',issueFr:'les horaires idéaux ne sont pas proposés chaque semaine',issueZh:'理想时段并非每周都有',solutionFr:'combiner un cours régulier et des séances autonomes',solutionZh:'结合固定课程与自主练习',words:[['une formation','n. f.','培训课程'],['un suivi','n. m.','跟进指导'],['autonome','adj.','自主的']]},
  {key:'reunion',topic:'work',titleZh:'准备一次有效会议',titleFr:'Préparer une réunion utile',placeFr:'au bureau',placeZh:'办公室',partner:'Collègue',requestFr:'préparer une réunion de décision',requestZh:'准备决策会议',detailFr:'distinguer les informations des points à trancher',detailZh:'区分信息与待决事项',issueFr:'l’ordre du jour contient trop de sujets',issueZh:'议程事项过多',solutionFr:'prioriser deux décisions et envoyer les documents à l’avance',solutionZh:'优先处理两项决定并提前发送材料',words:[['un ordre du jour','n. m.','议程'],['trancher','v.','作出决定'],['prioriser','v.','确定优先级']]},
  {key:'presentation',topic:'work',titleZh:'让演示更清楚',titleFr:'Rendre une présentation plus claire',placeFr:'dans une salle de réunion',placeZh:'会议室',partner:'Collègue',requestFr:'simplifier une présentation',requestZh:'简化一份演示',detailFr:'faire comprendre trois idées essentielles',detailZh:'让听众理解三个核心观点',issueFr:'les diapositives contiennent trop de détails',issueZh:'幻灯片细节过多',solutionFr:'déplacer les données secondaires dans une annexe',solutionZh:'把次要数据移入附录',words:[['une diapositive','n. f.','幻灯片'],['une annexe','n. f.','附录'],['essentiel','adj.','核心的']]},
  {key:'stage',topic:'work',titleZh:'申请实习机会',titleFr:'Candidater à un stage',placeFr:'dans une entreprise',placeZh:'企业',partner:'Responsable',requestFr:'présenter une candidature de stage',requestZh:'提交实习申请',detailFr:'relier ses compétences aux missions proposées',detailZh:'把自己的能力与岗位任务联系起来',issueFr:'l’expérience professionnelle est encore limitée',issueZh:'工作经验仍然有限',solutionFr:'mettre en valeur un projet concret et sa méthode',solutionZh:'突出一个具体项目及其方法',words:[['une candidature','n. f.','申请'],['une compétence','n. f.','能力'],['une mission','n. f.','工作任务']]},
  {key:'priorites',topic:'work',titleZh:'协商工作优先级',titleFr:'Négocier les priorités',placeFr:'au travail',placeZh:'工作场所',partner:'Responsable',requestFr:'clarifier plusieurs demandes urgentes',requestZh:'澄清多项紧急任务',detailFr:'protéger la qualité sans ignorer les délais',detailZh:'兼顾质量与期限',issueFr:'tout est présenté comme prioritaire',issueZh:'所有事项都被说成优先',solutionFr:'comparer l’impact, l’échéance et les ressources disponibles',solutionZh:'比较影响、期限和可用资源',words:[['une priorité','n. f.','优先事项'],['une échéance','n. f.','期限'],['une ressource','n. f.','资源']]},
  {key:'feedback',topic:'work',titleZh:'给出建设性反馈',titleFr:'Donner un retour constructif',placeFr:'après un projet',placeZh:'项目结束后',partner:'Collègue',requestFr:'faire un retour sur un travail collectif',requestZh:'就团队工作提供反馈',detailFr:'reconnaître les réussites et préciser un point à améliorer',detailZh:'肯定成果并指出一项改进点',issueFr:'une remarque générale peut être mal comprise',issueZh:'笼统意见可能被误解',solutionFr:'décrire un fait, son effet et une piste concrète',solutionZh:'描述事实、影响与具体建议',words:[['un retour','n. m.','反馈'],['constructif','adj.','建设性的'],['une piste','n. f.','思路；方向']]},
  {key:'enfance',topic:'stories',titleZh:'讲述童年习惯',titleFr:'Raconter une habitude d’enfance',placeFr:'dans son village',placeZh:'童年居住地',partner:'Ami',requestFr:'raconter un souvenir d’enfance',requestZh:'讲述一段童年回忆',detailFr:'décrire une habitude et un événement particulier',detailZh:'描述一个习惯和一次特殊事件',issueFr:'les souvenirs mélangent parfois plusieurs périodes',issueZh:'记忆有时混合多个时期',solutionFr:'distinguer le contexte habituel de l’événement précis',solutionZh:'区分日常背景和具体事件',words:[['un souvenir','n. m.','回忆'],['une habitude','n. f.','习惯'],['autrefois','adv.','从前']]},
  {key:'weekend',topic:'stories',titleZh:'复盘一次周末出行',titleFr:'Raconter un week-end',placeFr:'à la campagne',placeZh:'乡间',partner:'Amie',requestFr:'raconter un week-end inattendu',requestZh:'讲述一次意外的周末经历',detailFr:'expliquer le programme initial et ce qui a changé',detailZh:'说明原计划及变化',issueFr:'la pluie a modifié plusieurs activités',issueZh:'下雨改变了多项活动',solutionFr:'transformer le contretemps en nouvelle découverte',solutionZh:'把意外转化为新的发现',words:[['un contretemps','n. m.','意外耽搁'],['prévu','adj.','预定的'],['finalement','adv.','最后']]},
  {key:'erreur',topic:'stories',titleZh:'从一次错误中学习',titleFr:'Apprendre d’une erreur',placeFr:'pendant un projet',placeZh:'项目中',partner:'Collègue',requestFr:'expliquer une erreur et ses conséquences',requestZh:'说明一次错误及其后果',detailFr:'montrer ce qui a été corrigé ensuite',detailZh:'说明之后如何纠正',issueFr:'plusieurs causes ont contribué au problème',issueZh:'多个原因共同造成问题',solutionFr:'séparer les faits, les causes possibles et les changements adoptés',solutionZh:'区分事实、可能原因与采取的改变',words:[['une erreur','n. f.','错误'],['une conséquence','n. f.','后果'],['corriger','v.','纠正']]},
  {key:'reussite',topic:'stories',titleZh:'解释一次成功',titleFr:'Expliquer une réussite',placeFr:'à la fin d’un projet',placeZh:'项目结束时',partner:'Mentor',requestFr:'présenter une réussite sans la simplifier',requestZh:'介绍一次成功而不过度简化',detailFr:'reconnaître le rôle de la préparation et de l’équipe',detailZh:'承认准备与团队的作用',issueFr:'le résultat final masque les difficultés intermédiaires',issueZh:'最终结果掩盖了中间困难',solutionFr:'raconter les ajustements et les contributions précises',solutionZh:'讲述调整过程与具体贡献',words:[['une réussite','n. f.','成功'],['une contribution','n. f.','贡献'],['un ajustement','n. m.','调整']]},
  {key:'rencontre',topic:'stories',titleZh:'讲述一次重要相遇',titleFr:'Raconter une rencontre marquante',placeFr:'lors d’un atelier',placeZh:'工作坊中',partner:'Ami',requestFr:'raconter une rencontre qui a changé un projet',requestZh:'讲述一次改变项目的相遇',detailFr:'expliquer ce qui a été dit et ce qui a changé ensuite',detailZh:'说明对话内容及后续变化',issueFr:'le souvenir actuel est influencé par la suite des événements',issueZh:'现在的回忆受后续事件影响',solutionFr:'distinguer le moment vécu de son interprétation actuelle',solutionZh:'区分当时经历与现在的解释',words:[['marquant','adj.','印象深刻的'],['une interprétation','n. f.','解释'],['par la suite','loc. adv.','后来']]},
  {key:'invitation',topic:'social',titleZh:'安排一次朋友聚会',titleFr:'Organiser une rencontre entre amis',placeFr:'dans un parc',placeZh:'公园',partner:'Amie',requestFr:'organiser une rencontre le week-end',requestZh:'安排周末聚会',detailFr:'trouver un horaire et une activité accessibles',detailZh:'找到合适的时间和活动',issueFr:'les participants ont des contraintes différentes',issueZh:'参与者限制不同',solutionFr:'proposer deux options et fixer une date de réponse',solutionZh:'提出两个选项并设定回复时间',words:[['une disponibilité','n. f.','空闲时间'],['une contrainte','n. f.','限制'],['confirmer','v.','确认']]},
  {key:'benevolat',topic:'social',titleZh:'加入社区志愿活动',titleFr:'Participer à une action bénévole',placeFr:'dans une association',placeZh:'协会',partner:'Coordinatrice',requestFr:'participer à une action bénévole',requestZh:'参加志愿活动',detailFr:'choisir une tâche compatible avec son temps',detailZh:'选择与个人时间相符的任务',issueFr:'les besoins varient chaque semaine',issueZh:'每周需求都会变化',solutionFr:'définir un engagement réaliste et un moyen de prévenir',solutionZh:'确定现实的投入方式和通知机制',words:[['bénévole','adj. et n.','志愿的；志愿者'],['un engagement','n. m.','投入；承诺'],['prévenir','v.','提前通知']]},
  {key:'club',topic:'social',titleZh:'为社团设计活动',titleFr:'Proposer une activité au club',placeFr:'dans un club culturel',placeZh:'文化社团',partner:'Membre',requestFr:'proposer une nouvelle activité',requestZh:'提出一项新活动',detailFr:'attirer de nouveaux membres sans exclure les anciens',detailZh:'吸引新成员而不排斥老成员',issueFr:'les attentes du groupe sont très diverses',issueZh:'成员期待差异很大',solutionFr:'organiser une séance pilote et recueillir des retours précis',solutionZh:'组织试行活动并收集具体反馈',words:[['un membre','n. m.','成员'],['une séance pilote','n. f.','试行活动'],['un retour','n. m.','反馈']]},
  {key:'fete',topic:'social',titleZh:'共同筹备庆祝活动',titleFr:'Préparer une fête ensemble',placeFr:'dans une salle commune',placeZh:'公共活动室',partner:'Organisatrice',requestFr:'répartir la préparation d’une fête',requestZh:'分配庆祝活动的准备工作',detailFr:'respecter le budget et les préférences du groupe',detailZh:'遵守预算并兼顾成员偏好',issueFr:'certaines tâches sont moins visibles mais indispensables',issueZh:'有些任务不显眼却必不可少',solutionFr:'attribuer les responsabilités et reconnaître chaque contribution',solutionZh:'分配责任并认可每项贡献',words:[['un budget','n. m.','预算'],['une responsabilité','n. f.','责任'],['indispensable','adj.','不可或缺的']]},
  {key:'conflit',topic:'social',titleZh:'化解群组中的误会',titleFr:'Clarifier un malentendu',placeFr:'dans un groupe',placeZh:'群组中',partner:'Membre',requestFr:'clarifier un message mal interprété',requestZh:'澄清一条被误解的消息',detailFr:'rétablir les faits sans accuser',detailZh:'澄清事实而不指责',issueFr:'le ton écrit paraît plus dur que prévu',issueZh:'文字语气比预期更强硬',solutionFr:'reformuler l’intention et demander comment le message a été reçu',solutionZh:'重述意图并询问对方如何理解',words:[['un malentendu','n. m.','误会'],['reformuler','v.','重新表述'],['une intention','n. f.','意图']]},
  {key:'ecrans',topic:'opinions',titleZh:'讨论屏幕使用',titleFr:'Réfléchir au temps d’écran',placeFr:'en famille',placeZh:'家庭中',partner:'Parent',requestFr:'discuter du temps passé devant les écrans',requestZh:'讨论屏幕使用时间',detailFr:'distinguer travail, apprentissage et distraction',detailZh:'区分工作、学习和娱乐',issueFr:'un seul chiffre ne décrit pas tous les usages',issueZh:'单一时长无法描述所有使用方式',solutionFr:'observer les effets et fixer des règles selon les situations',solutionZh:'观察影响并按情境设定规则',words:[['le temps d’écran','n. m.','屏幕使用时间'],['un usage','n. m.','使用方式'],['une distraction','n. f.','娱乐；分心事物']]},
  {key:'transport',topic:'opinions',titleZh:'比较城市交通方案',titleFr:'Comparer des solutions de transport',placeFr:'dans la ville',placeZh:'城市中',partner:'Habitante',requestFr:'comparer plusieurs modes de transport',requestZh:'比较多种交通方式',detailFr:'tenir compte du coût, du temps et de l’accessibilité',detailZh:'考虑价格、时间和无障碍性',issueFr:'la meilleure option varie selon les quartiers',issueZh:'最佳方案因街区而异',solutionFr:'définir des critères communs puis tester plusieurs trajets',solutionZh:'确定共同标准并测试多条路线',words:[['l’accessibilité','n. f.','可达性；无障碍性'],['un trajet','n. m.','行程'],['un critère','n. m.','标准']]},
  {key:'climat',topic:'opinions',titleZh:'讨论个人与集体行动',titleFr:'Agir à son échelle et collectivement',placeFr:'dans le quartier',placeZh:'社区',partner:'Habitant',requestFr:'choisir une action environnementale utile',requestZh:'选择一项有用的环保行动',detailFr:'relier les habitudes individuelles aux décisions collectives',detailZh:'把个人习惯与集体决策联系起来',issueFr:'les gestes visibles ne sont pas toujours les plus efficaces',issueZh:'最显眼的行动不一定最有效',solutionFr:'comparer l’impact, la faisabilité et la durée',solutionZh:'比较影响、可行性和持续时间',words:[['un impact','n. m.','影响'],['la faisabilité','n. f.','可行性'],['collectif','adj.','集体的']]},
  {key:'culture',topic:'opinions',titleZh:'讨论文化活动的可及性',titleFr:'Rendre la culture plus accessible',placeFr:'dans un centre culturel',placeZh:'文化中心',partner:'Directrice',requestFr:'améliorer l’accès aux activités culturelles',requestZh:'改善文化活动的可及性',detailFr:'agir sur le prix, les horaires et l’information',detailZh:'从价格、时间和信息入手',issueFr:'une mesure unique ne répond pas à tous les obstacles',issueZh:'单一措施无法解决所有障碍',solutionFr:'combiner plusieurs actions et évaluer qui en bénéficie',solutionZh:'结合多项措施并评估受益群体',words:[['l’accès','n. m.','获取机会；进入'],['un obstacle','n. m.','障碍'],['bénéficier de','v.','受益于']]},
  {key:'education',topic:'opinions',titleZh:'评估一种学习方法',titleFr:'Évaluer une méthode d’apprentissage',placeFr:'dans une école',placeZh:'学校',partner:'Enseignante',requestFr:'évaluer une nouvelle méthode d’apprentissage',requestZh:'评估一种新的学习方法',detailFr:'observer les progrès sans ignorer les différences de départ',detailZh:'观察进步而不忽略起点差异',issueFr:'les résultats peuvent avoir plusieurs explications',issueZh:'结果可能有多种解释',solutionFr:'comparer des indicateurs variés et rendre les limites visibles',solutionZh:'比较多种指标并明确局限',words:[['une méthode','n. f.','方法'],['un indicateur','n. m.','指标'],['une limite','n. f.','局限']]},
  {key:'information',topic:'opinions',titleZh:'核查一条网上信息',titleFr:'Vérifier une information en ligne',placeFr:'sur internet',placeZh:'网络上',partner:'Ami',requestFr:'vérifier une information avant de la partager',requestZh:'转发前核实信息',detailFr:'retrouver la source, la date et le contexte',detailZh:'找到来源、日期和语境',issueFr:'un message convaincant peut omettre des éléments importants',issueZh:'有说服力的信息也可能遗漏关键内容',solutionFr:'croiser les sources et distinguer fait, interprétation et incertitude',solutionZh:'交叉核对来源并区分事实、解释与不确定性',words:[['une source','n. f.','来源'],['croiser','v.','交叉核对'],['une incertitude','n. f.','不确定性']]},
];

const levelMinutes:Record<LearningLevel,number>={A1:12,A2:15,'A2+':18,B1:20,B2:24,C1:30,C2:36};
const suffix:Record<LearningLevel,string>={A1:'说清基本信息',A2:'补充实用细节','A2+':'连接原因与步骤',B1:'解释选择和经历',B2:'比较方案与限制',C1:'分析条件与立场',C2:'辨析语气与论证'};

function dialogue(level:LearningLevel,s:Scenario):Lesson['dialogue']{
  if(level==='A1')return [
    {speaker:s.partner,fr:'Bonjour. Je peux vous aider ?',zh:'您好。需要帮助吗？'},
    {speaker:'Vous',fr:`Oui, je voudrais ${s.requestFr}, s’il vous plaît.`,zh:`好的，我想${s.requestZh}。`},
    {speaker:s.partner,fr:`D’accord. Vous avez une demande précise ?`,zh:'好的。您有具体要求吗？'},
    {speaker:'Vous',fr:`Oui, je voudrais ${s.detailFr}.`,zh:`有，我希望${s.detailZh}。`},
    {speaker:s.partner,fr:`Très bien. Nous allons regarder cela ensemble.`,zh:'很好。我们一起来看看。'},
    {speaker:'Vous',fr:'Merci beaucoup. Pouvez-vous parler lentement ?',zh:'非常感谢。您可以说慢一点吗？'},
  ];
  if(level==='A2'||level==='A2+')return [
    {speaker:s.partner,fr:`Bonjour. Que souhaitez-vous faire ${s.placeFr} ?`,zh:`您好。您在${s.placeZh}想办理什么？`},
    {speaker:'Vous',fr:`Je voudrais ${s.requestFr}. Mon objectif est ${s.detailFr}.`,zh:`我想${s.requestZh}。我的目标是${s.detailZh}。`},
    {speaker:s.partner,fr:`Je comprends. Il faut cependant savoir que ${s.issueFr}.`,zh:`我明白。不过需要知道，${s.issueZh}。`},
    {speaker:'Vous',fr:`Dans ce cas, je préfère ${s.solutionFr}. Quelle est la première étape ?`,zh:`这样的话，我更希望${s.solutionZh}。第一步是什么？`},
    {speaker:s.partner,fr:'Je vais vous expliquer les possibilités, puis vous pourrez choisir.',zh:'我会先说明可选方案，然后您可以作选择。'},
    {speaker:'Vous',fr:'Parfait. Je vais noter les informations pour ne rien oublier.',zh:'很好。我会记下信息，免得遗漏。'},
  ];
  if(level==='B1')return [
    {speaker:s.partner,fr:`Vous souhaitez ${s.requestFr}. Qu’est-ce qui compte le plus pour vous ?`,zh:`您希望${s.requestZh}。对您来说最重要的是什么？`},
    {speaker:'Vous',fr:`Je voudrais surtout ${s.detailFr}, parce que cela répond à ma situation actuelle.`,zh:`我最希望${s.detailZh}，因为这符合我目前的情况。`},
    {speaker:s.partner,fr:`Il faut tout de même tenir compte d’un point : ${s.issueFr}.`,zh:`不过仍需考虑一点：${s.issueZh}。`},
    {speaker:'Vous',fr:`Je le comprends. C’est pourquoi je propose de ${s.solutionFr}.`,zh:`我理解。因此我建议${s.solutionZh}。`},
    {speaker:s.partner,fr:'Cette proposition paraît réaliste. Comment vérifierons-nous qu’elle fonctionne ?',zh:'这个建议看起来可行。我们怎样确认它有效？'},
    {speaker:'Vous',fr:'Nous pouvons fixer une étape de contrôle et adapter la solution à partir des résultats.',zh:'可以设定一个检查节点，再根据结果调整方案。'},
  ];
  if(level==='B2')return [
    {speaker:s.partner,fr:`La demande consiste à ${s.requestFr}. Certains défendent une solution immédiate.`,zh:`需求是${s.requestZh}。有人主张立即采用一种方案。`},
    {speaker:'Vous',fr:`Cette approche a un avantage, puisqu’elle permet de ${s.detailFr}. Elle ne suffit pourtant pas à elle seule.`,zh:`这种做法有一个优点，因为能够${s.detailZh}。但仅凭这一点还不够。`},
    {speaker:s.partner,fr:`Vous pensez sans doute à la difficulté suivante : ${s.issueFr}.`,zh:`您大概考虑到这个困难：${s.issueZh}。`},
    {speaker:'Vous',fr:`Exactement. On pourrait plutôt ${s.solutionFr}, tout en définissant des critères d’évaluation.`,zh:`正是。可以改为${s.solutionZh}，同时确定评价标准。`},
    {speaker:s.partner,fr:'Cette solution demande plus d’organisation. Pourquoi serait-elle préférable ?',zh:'这个方案需要更多组织工作。为什么更好？'},
    {speaker:'Vous',fr:'Elle rend les contraintes visibles et permet de réviser le choix si les effets attendus ne se réalisent pas.',zh:'它能让限制条件清楚可见，并在预期效果未出现时允许修改选择。'},
  ];
  if(level==='C1')return [
    {speaker:s.partner,fr:`À première vue, il suffirait de ${s.requestFr}. Le dossier insiste surtout sur la nécessité de ${s.detailFr}.`,zh:`初看似乎只要${s.requestZh}即可。材料主要强调需要${s.detailZh}。`},
    {speaker:'Vous',fr:'Cette formulation présente l’objectif comme allant de soi, alors que ses conditions restent partiellement implicites.',zh:'这种表述把目标呈现为理所当然，但它的条件仍有一部分是隐含的。'},
    {speaker:s.partner,fr:`La principale réserve serait que ${s.issueFr}. Faut-il pour autant renoncer ?`,zh:`主要保留意见是${s.issueZh}。是否因此就该放弃？`},
    {speaker:'Vous',fr:`Pas nécessairement. On pourrait ${s.solutionFr}, à condition de préciser qui évalue les résultats et selon quels critères.`,zh:`未必。可以${s.solutionZh}，前提是说明谁来评价结果以及依据什么标准。`},
    {speaker:s.partner,fr:'Vous distinguez donc l’accord sur le principe de l’engagement sur les moyens.',zh:'所以您区分了原则上的同意与资源上的承诺。'},
    {speaker:'Vous',fr:'Oui. Cette distinction évite de transformer une orientation générale en promesse déjà acquise.',zh:'是的。这一区分可以避免把总体方向改写成已经作出的承诺。'},
  ];
  return [
    {speaker:s.partner,fr:`Le texte donne à penser qu’il suffirait de ${s.requestFr}, comme si la finalité de ${s.detailFr} rendait la méthode incontestable.`,zh:`文本让人以为只要${s.requestZh}即可，仿佛${s.detailZh}这一目标使方法不容质疑。`},
    {speaker:'Vous',fr:'Le glissement est discret : une intention jugée souhaitable tient progressivement lieu de preuve quant à l’efficacité du dispositif.',zh:'这种滑移很细微：一个被认为值得追求的意图，逐渐代替了对方案有效性的证明。'},
    {speaker:s.partner,fr:`L’objection selon laquelle ${s.issueFr} suffit-elle à invalider l’ensemble ?`,zh:`“${s.issueZh}”这一异议足以推翻全部论点吗？`},
    {speaker:'Vous',fr:`Non. Elle oblige plutôt à reformuler la portée de la conclusion et à envisager de ${s.solutionFr} sans présumer du résultat.`,zh:`不。它更要求我们重写结论的适用范围，并考虑${s.solutionZh}，而不预设结果。`},
    {speaker:s.partner,fr:'Comment préserver cette nuance dans une synthèse destinée à un public non spécialiste ?',zh:'面向非专业读者的综合文本怎样保留这种细微差别？'},
    {speaker:'Vous',fr:'En séparant les faits, les interprétations et les conditions, puis en indiquant quel changement de preuve modifierait raisonnablement le jugement.',zh:'区分事实、解释与条件，再说明什么样的新证据会合理地改变判断。'},
  ];
}

function writing(level:LearningLevel,s:Scenario):Lesson['writing']{
  if(level==='A1')return {prompt:`用 20–40 词写一条消息：说明你在${s.placeZh}想做什么，并提出一个简单问题。`,example:`Bonjour. Je voudrais ${s.requestFr}. Je suis ${s.placeFr}. Mon objectif est ${s.detailFr}. Pouvez-vous m’aider et parler lentement, s’il vous plaît ? Merci beaucoup pour votre réponse.`};
  if(level==='A2')return {prompt:`用 40–80 词说明你想${s.requestZh}，补充具体需要并询问下一步。`,example:`Bonjour, je vous écris parce que je voudrais ${s.requestFr}. Je souhaite surtout ${s.detailFr}. Je sais que ${s.issueFr}, alors je voudrais connaître les possibilités. Est-ce que je peux ${s.solutionFr} ? Pouvez-vous m’expliquer la première étape et les documents nécessaires ? Je vous remercie pour votre aide et j’attends votre réponse.`,checklist:['我说明了具体需要和限制。','我提出了一个清楚、可以回答的问题。']};
  if(level==='A2+')return {prompt:`写 40–80 词：先说明情境，再用连接词解释困难、计划和下一步。`,example:`Bonjour, je voudrais ${s.requestFr}. D’abord, mon objectif est ${s.detailFr}. Cependant, je dois aussi tenir compte du fait que ${s.issueFr}. C’est pourquoi je préfère ${s.solutionFr}. Ensuite, je pourrai vérifier les informations et confirmer mon choix. Pourriez-vous me dire comment commencer et quand je recevrai une réponse ? Merci d’avance pour vos conseils.`,checklist:['我用连接词清楚排列了步骤。','我解释了选择这一方案的原因。']};
  if(level==='B1')return {prompt:`写 40–80 词解释你在这一情境中的选择、理由和一个具体例子。`,example:`Je souhaite ${s.requestFr}, car il est important pour moi de ${s.detailFr}. La situation n’est pourtant pas simple : ${s.issueFr}. Par exemple, un choix trop rapide pourrait créer une nouvelle difficulté. Je propose donc de ${s.solutionFr}. Cette solution me paraît réaliste parce qu’elle permet de vérifier les résultats avant de continuer. Si elle ne fonctionne pas, nous pourrons l’adapter ensemble.`,checklist:['我给出了选择、理由和具体例子。','我说明了方案无效时如何调整。']};
  if(level==='B2')return {prompt:`写 100–160 词比较两个方案，承认一项反对意见，并提出评价标准。`,example:`La situation nous oblige à décider comment ${s.requestFr}. Une réponse immédiate présente un avantage évident : elle permet de ${s.detailFr}. Elle donne aussi aux personnes concernées un repère clair. Cependant, cette solution ne tient pas suffisamment compte du fait que ${s.issueFr}. L’appliquer sans précaution risquerait donc de déplacer le problème plutôt que de le résoudre.\nJe propose plutôt de ${s.solutionFr}. Certes, cette méthode demande un peu plus d’organisation, mais elle rend les contraintes visibles et permet de corriger le choix. Nous devrions définir à l’avance deux critères : l’effet concret sur les personnes concernées et le temps nécessaire pour obtenir ce résultat. Une période d’essai, suivie d’un bilan, aiderait à comparer les intentions aux effets observés. La décision finale reposerait ainsi sur des éléments vérifiables, tout en restant révisable si la situation change.`,checklist:['我比较了至少两个方案，没有只宣布偏好。','我承认了一项合理异议，并提出了可观察的评价标准。']};
  if(level==='C1')return {prompt:`写 180–240 词的正式分析：区分原则、条件和承诺，提出可复审的方案。`,example:`La proposition étudiée vise à ${s.requestFr}. Son objectif paraît légitime, notamment parce qu’elle cherche à ${s.detailFr}. Cette adhésion de principe ne permet toutefois pas de conclure que les modalités sont déjà acceptées. Plusieurs responsabilités, ressources et critères d’évaluation restent à préciser.\nLa principale réserve tient au fait que ${s.issueFr}. Il serait excessif d’en déduire que le projet doit être abandonné. Inversement, présenter cette difficulté comme un simple détail reviendrait à transformer une orientation générale en engagement sans condition. Le texte final devrait donc distinguer ce qui fait l’objet d’un accord, ce qui demeure une hypothèse et ce qui nécessite une décision supplémentaire.\nUne piste consisterait à ${s.solutionFr}. Cette démarche devrait préciser qui recueille les informations, selon quelle méthode et à quel moment les résultats seront examinés. Les personnes concernées devraient également pouvoir signaler un effet inattendu sans attendre la fin de l’expérimentation.\nLe bilan ne saurait reposer sur un seul indicateur. Il devrait combiner l’effet recherché, les contraintes créées et la manière dont leurs conséquences se répartissent. Une amélioration moyenne pourrait en effet masquer une difficulté concentrée sur un groupe moins visible.\nÀ ce stade, il est donc possible de recommander une mise à l’essai limitée, sans présumer de son issue. La poursuite du dispositif dépendrait des éléments recueillis et d’une décision explicitement motivée. Cette formulation préserve l’objectif initial tout en rendant les conditions de l’accord discutables et révisables.`,checklist:['我区分了原则性支持、实施条件和已经作出的承诺。','我明确了资料收集、责任和复审节点。','我保留了不确定性，没有把试行写成已证明有效。']};
  return {prompt:`写 240–320 词的批判性综合：分析措辞、隐含前提和证据边界，并给出不扩大承诺的重述。`,example:`Le passage consacré à la nécessité de ${s.requestFr} semble d’abord présenter une démarche pratique. Il associe cette démarche à une finalité valorisée, celle de ${s.detailFr}. Or le lien entre une intention souhaitable et l’efficacité de la méthode n’est pas démontré par leur simple proximité dans le texte. La formulation invite le lecteur à accepter la seconde au nom de la première.\nCette construction repose sur un présupposé : dès lors que l’objectif est jugé légitime, les moyens proposés seraient adaptés. L’objection selon laquelle ${s.issueFr} ne suffit pas, à elle seule, à prouver l’inverse. Elle révèle néanmoins une condition que l’argument initial laissait hors champ. Il faut donc résister à deux conclusions symétriques : considérer le projet comme nécessaire parce que son but est séduisant, ou le déclarer inutile dès qu’une limite apparaît.\nUne reformulation plus rigoureuse proposerait de ${s.solutionFr}, sans annoncer d’avance le résultat. Elle préciserait la période observée, les personnes chargées de l’évaluation et les conséquences susceptibles d’être révisées. Elle distinguerait aussi une amélioration globale d’une distribution équitable des effets. Ce qui paraît positif en moyenne peut imposer une charge disproportionnée à un groupe particulier.\nLe choix des mots mérite lui aussi d’être contrôlé. Des verbes tels que « garantir », « résoudre » ou « permettre » n’expriment pas le même degré de certitude. S’il ne s’agit encore que d’une hypothèse, il serait préférable d’écrire que la mesure « pourrait contribuer à » l’objectif, sous des conditions nommées.\nUne synthèse destinée au public pourrait ainsi présenter les faits établis, les interprétations en présence et les informations manquantes dans trois mouvements distincts. Elle conserverait la raison d’agir sans faire de cette urgence une preuve. Elle indiquerait enfin quel nouvel élément justifierait de poursuivre, de modifier ou d’abandonner le dispositif. La nuance ne consiste pas à éviter toute conclusion ; elle consiste à donner à la conclusion une portée proportionnée aux éléments réellement disponibles.`,checklist:['我区分了事实、解释和隐含前提。','我分析了动词力度，没有虚构作者意图。','我的重述保留了核心问题，却没有提高确定性。']};
}

function grammar(level:LearningLevel,index:number):Lesson['grammar']{
  const variants:Record<LearningLevel,Lesson['grammar'][]>= {
    A1:[
      {title:'Je voudrais + 不定式',explanation:'je voudrais 可以礼貌地表达愿望，后面直接接动词原形。',example:'Je voudrais envoyer un colis.',translation:'我想寄一个包裹。',question:'补全：Je voudrais ___ une information.',options:['demande','demander','demandé'],answer:1,why:'voudrais 后接动词不定式 demander。'},
      {title:'Pouvez-vous… ?',explanation:'pouvez-vous + 动词原形可以礼貌地请求对方做某事。',example:'Pouvez-vous parler lentement ?',translation:'您可以说慢一点吗？',question:'补全：Pouvez-vous ___ ?',options:['répétez','répéter','répété'],answer:1,why:'pouvez-vous 后接不定式 répéter。'},
    ],
    A2:[{title:'parce que 表示原因',explanation:'parce que 引出具体原因，帮助把两个简单信息连接起来。',example:'Je vous écris parce que j’ai une question.',translation:'我给您写信，因为我有一个问题。',question:'选择正确连接词：Je téléphone ___ j’ai besoin d’aide.',options:['mais','parce que','ensuite'],answer:1,why:'后半句说明打电话的原因。'}],
    'A2+':[{title:'d’abord、ensuite、enfin',explanation:'这些连接词可以清楚地组织步骤和时间顺序。',example:'D’abord, je vérifie. Ensuite, je confirme.',translation:'首先我核实，然后确认。',question:'哪个词最适合引出第二步？',options:['Ensuite','Parce que','Pourtant'],answer:0,why:'ensuite 用于引出后续步骤。'}],
    B1:[{title:'c’est pourquoi 表示结果',explanation:'c’est pourquoi 承接前文原因，引出由此作出的选择或结果。',example:'La situation est complexe. C’est pourquoi je propose un essai.',translation:'情况复杂。因此我建议试行。',question:'哪个表达引出前文原因的结果？',options:['C’est pourquoi','Même si','Avant que'],answer:0,why:'c’est pourquoi 相当于“因此”。'}],
    B2:[{title:'certes… mais… 表达让步',explanation:'certes 承认一项事实，mais 随后限定其影响或提出反面考虑。',example:'Certes, la méthode est simple, mais elle a des limites.',translation:'这种方法确实简单，但也有局限。',question:'这组结构的主要作用是什么？',options:['列举时间顺序','承认一点后提出限制','表达确定的因果'],answer:1,why:'certes… mais… 组织让步关系。'}],
    C1:[{title:'sans que + 虚拟式',explanation:'sans que 引出没有发生或未被确认的情况，后面使用虚拟式。',example:'On peut avancer sans que le résultat soit garanti.',translation:'可以推进，但结果并不保证。',question:'补全：sans que la décision ___ définitive',options:['est','soit','sera'],answer:1,why:'sans que 后使用虚拟式 soit。'}],
    C2:[{title:'ne… pas à lui seul：限制证据力度',explanation:'à lui seul 强调某一因素单独作用；放入否定结构可说明它不足以独立支持结论。',example:'Cet exemple ne suffit pas à lui seul à prouver la règle.',translation:'仅凭这个例子不足以证明该规则。',question:'这句话排除了哪一种推论？',options:['该例子完全无关','单个例子足以独立证明普遍规则','还可以继续寻找证据'],answer:1,why:'否定的是单一证据独立证明结论的充分性。'}],
  };
  return variants[level][index%variants[level].length];
}

function build(level:LearningLevel,s:Scenario,index:number):Lesson{
  const id=`scale-${level.toLowerCase().replace('+','p')}-${String(index+1).padStart(2,'0')}`;
  return {
    id,topic:s.topic,level,title:`${s.titleZh}：${suffix[level]}`,fr:s.titleFr,
    goal:level==='A1'?`在${s.placeZh}用简短句子表达需要并提出问题。`:level==='A2'?`在${s.placeZh}说明需要、限制和下一步。`:level==='A2+'?`用连接词组织${s.requestZh}的原因与步骤。`:level==='B1'?`围绕${s.requestZh}解释选择、原因和结果。`:level==='B2'?`围绕${s.requestZh}比较方案并回应限制。`:level==='C1'?`分析${s.requestZh}中的隐含条件、责任与承诺。`:`辨析${s.requestZh}相关文本的语气、前提与证据边界。`,
    minutes:levelMinutes[level],dialogue:dialogue(level,s),words:s.words.map(([fr,pos,zh],i)=>({id:`${id}-word-${i+1}`,fr,pos,zh})),grammar:grammar(level,index),
    quiz:{question:'本课最终建议的做法是什么？',options:[`忽略所有限制，立即${s.requestZh}`,s.solutionZh,'完全停止讨论'],answer:1,why:`对话建议${s.solutionZh}，并保留检查或调整的空间。`},
    ...(level==='A1'?{}:{readingTask:{prompt:level==='C2'?'区分对话中的明确事实、隐含前提和仍需证实的判断。改变哪个词会显著加强承诺？':level==='C1'?'对话在哪些地方区分了原则上的赞同、实施条件和实际承诺？':'说话人承认了哪项限制？这一限制怎样改变最终建议？',answer:level==='C2'?`明确的情境是${s.issueZh}；文本仍需证明所选方法能够达到目标。把“可能”改为“保证”等词会明显提高承诺强度。`:level==='C1'?`说话人接受${s.detailZh}这一目标，但把${s.issueZh}作为实施条件，并主张${s.solutionZh}，所以没有把方向性支持写成既定结果。`:`说话人承认${s.issueZh}，因此没有直接接受最初方案，而是建议${s.solutionZh}。`}}),
    writing:writing(level,s),
  };
}

const existingCounts:Record<LearningLevel,number>={A1:8,A2:7,'A2+':8,B1:9,B2:8,C1:8,C2:8};
const topicOrder=['daily','food','travel','home','work','stories','social','opinions'];
const balancedScenarios=Array.from({length:6},(_,round)=>topicOrder.map(topic=>scenarios.filter(s=>s.topic===topic)[round])).flat().filter((scenario):scenario is Scenario=>Boolean(scenario));
export const scaledLessons:Lesson[]=(Object.keys(existingCounts) as LearningLevel[]).flatMap(level=>
  balancedScenarios.slice(0,50-existingCounts[level]).map((scenario,index)=>build(level,scenario,index)),
);
export const scaledScenarioCount=balancedScenarios.length;
