import {createLessons} from './course-authoring';

export const b2Lessons=createLessons('B2',33,[
  {
    topic:'daily',title:'在社区讨论中提出建议',fr:'Un quartier plus calme, mais vivant',goal:'在承认他人需求的同时，为自己的建议提供理由。',minutes:22,
    dialogue:[
      ['Voisine','La terrasse du café attire du monde, mais le bruit nous empêche de dormir. Certains voisins demandent sa fermeture.','咖啡馆露台吸引了很多人，但噪音让我们睡不着。一些邻居要求关闭它。'],
      ['Vous','Je comprends leur fatigue. Pourtant, fermer la terrasse supprimerait aussi un lieu de rencontre. Pourquoi ne pas limiter les horaires ?','我理解他们的疲惫。不过，关闭露台也会让大家失去一个见面场所。为什么不限制营业时间呢？'],
      ['Voisine','Le propriétaire affirme qu’une fermeture plus tôt ferait baisser son chiffre d’affaires. Comment répondre à cette objection ?','店主说提前关门会减少营业额。该怎样回应这个反对意见？'],
      ['Vous','On pourrait tester la fermeture à vingt-deux heures pendant un mois, tout en autorisant une soirée plus longue le samedi.','可以试行一个月，每晚十点关闭，但允许周六延长一次。'],
      ['Voisine','Ce serait donc une période d’essai, pas une règle définitive. Comment saurons-nous si elle fonctionne ?','那就是试行，而不是永久规则。我们怎么知道有没有效果？'],
      ['Vous','Demandons aux riverains de noter les nuisances et au café de présenter un bilan. Ensuite, nous déciderons ensemble à partir de ces éléments.','请附近居民记录干扰，也请咖啡馆提供总结。然后大家根据这些信息一起决定。'],
    ],
    words:[['une nuisance','n. f.','扰民因素；干扰'],['une période d’essai','n. f.','试行期'],['un riverain','n. m.','附近居民']],
    grammar:{title:'tout en + 分词：兼顾两项行动',explanation:'tout en suivi du participe présent 可以连接同时发生的行动，也能突出两种需求之间的张力。两部分的行动者应一致。',example:'On limite les horaires tout en maintenant un lieu de rencontre.',translation:'限制营业时间，同时保留一个交流场所。',question:'哪一句表示“减少噪音，同时保留露台”？',options:['On réduit le bruit pour fermer la terrasse.','On réduit le bruit tout en conservant la terrasse.','On réduit le bruit parce que la terrasse a disparu.'],answer:1,why:'tout en conservant 表示两项目标兼顾；另外两句分别是目的与原因。'},
    quiz:{question:'说话人建议如何判断方案的效果？',options:['只听店主意见','先永久关闭再讨论','试行并收集居民与店主的反馈'],answer:2,why:'双方将记录 nuisances、提交 bilan，再依据这些信息作决定。'},
    readingTask:{prompt:'“Pourtant”之后引入了哪一种被忽略的利益？为什么试行比立即关闭更容易达成一致？',answer:'转折引入咖啡馆作为社区交流空间的作用。试行有期限且有评价依据，让居民与经营者不必立刻接受永久结果。'},
    writing:{prompt:'给社区写一封 100–160 词的建议邮件，说明噪音问题、回应店主的一项顾虑，并提出有期限的试行和评价方式。',example:'Madame, Monsieur,\nJe vous écris au sujet du bruit autour de la terrasse. Plusieurs habitants dorment mal, surtout lorsque les conversations continuent après vingt-trois heures. Leur demande me semble donc légitime. Cependant, le café joue aussi un rôle dans la vie du quartier. Une fermeture complète serait une réponse excessive.\nJe propose de tester une fermeture à vingt-deux heures pendant un mois, avec une exception le samedi. Certes, cette mesure pourrait réduire certaines recettes, mais elle permettrait de maintenir la terrasse. Les habitants pourraient noter les nuisances et le propriétaire préparer un bilan. Une réunion ouverte servirait ensuite à adapter les horaires. Nous disposerions ainsi de faits concrets avant de fixer une règle durable.\nCordialement,',checklist:['我承认了另一方的一项合理顾虑。','我提出了具体方案、期限和评价方式。']},
  },
  {
    topic:'food',title:'少包装，还是更方便？',fr:'Le vrac au quotidien',goal:'比较购物方式的优缺点，用条件限制自己的结论。',minutes:22,
    dialogue:[
      ['Amie','Depuis que j’achète en vrac, je jette moins d’emballages. Je pense que tout le monde devrait faire pareil.','自从买散装商品后，我扔掉的包装少了。我觉得大家都该这样做。'],
      ['Vous','L’idée me plaît, mais elle dépend des habitudes et des magasins disponibles. Près de chez moi, le rayon en vrac est assez limité.','我喜欢这个想法，但要看习惯和附近的商店。我家附近的散装货架选择很少。'],
      ['Amie','On peut prendre le bus pour aller dans une boutique spécialisée. Ce n’est pas forcément très compliqué.','可以坐公交去专门的店。也不一定很麻烦。'],
      ['Vous','C’est vrai pour certaines personnes. En revanche, quelqu’un qui travaille tard peut manquer de temps. Il faudrait aussi comparer le prix au kilo.','对一些人来说是这样。不过，工作到很晚的人可能没有时间。也应该比较每公斤价格。'],
      ['Amie','Alors, tu ne conseilles pas de changer ses habitudes ?','那你不建议改变习惯吗？'],
      ['Vous','Si, mais progressivement : choisir quelques produits, vérifier les prix et réutiliser les contenants. Une solution accessible sera plus facile à garder.','建议，但要循序渐进：选几样商品、查看价格、重复使用容器。可行的方案更容易坚持。'],
    ],
    words:[['en vrac','loc. adv.','散装出售'],['un contenant','n. m.','容器'],['en revanche','loc. adv.','相对而言；不过']],
    grammar:{title:'用 si 回应否定问句',explanation:'面对否定问句，用 si 可以推翻对方的否定。“Tu ne conseilles pas… ? — Si.” 表示“我建议”。',example:'Tu ne veux pas essayer ? — Si, mais progressivement.',translation:'你不想试试吗？——想，但要慢慢来。',question:'对“Tu ne conseilles pas de changer ?”回答“Si”，意思是什么？',options:['确实不建议改变','仍然建议改变','没有听懂问题'],answer:1,why:'si 在这里反驳否定前提，相当于“不是，我建议改变”。'},
    quiz:{question:'说话人的最终立场是什么？',options:['所有人马上完全改买散装','散装没有任何作用','按条件逐步尝试，比较价格并重复使用容器'],answer:2,why:'建议用 progressivement 限定改变的速度，并考虑可及性与价格。'},
    readingTask:{prompt:'找出一句让步和一句限制。它们如何使结论更谨慎？',answer:'“L’idée me plaît”承认优点；“elle dépend…”限定适用条件。说话人支持减少包装，但不把单一购物方式强加给所有人。'},
    writing:{prompt:'写 100–160 词回应“所有人都应该买散装”。至少比较两个条件，给出一个具体建议。',example:'Acheter en vrac peut aider à réduire les emballages, mais cette solution ne convient pas de la même manière à tous les ménages. D’une part, elle permet de choisir une quantité adaptée et de réutiliser ses contenants. D’autre part, certains habitants n’ont pas de magasin proche ou disposent de peu de temps pour faire leurs courses.\nIl serait donc utile de comparer le prix au kilo et le temps nécessaire, sans supposer que le vrac est toujours moins cher. Je conseillerais de commencer par deux ou trois produits faciles à conserver. On pourrait ensuite élargir ses achats si cette organisation fonctionne. Une habitude réaliste, maintenue dans la durée, me paraît préférable à un changement radical rapidement abandonné.',checklist:['我比较了至少两项实际条件。','我的结论有适用范围，没有使用未经支持的“总是”。']},
  },
  {
    topic:'travel',title:'旅行中提出合理投诉',fr:'Trouver une solution après une annulation',goal:'清楚陈述问题，协商替代方案而不是只表达不满。',minutes:22,
    dialogue:[
      ['Agent','Votre excursion est annulée en raison de la météo. Nous pouvons vous proposer un départ demain matin.','由于天气原因，您的游览取消了。我们可以安排明天早上出发。'],
      ['Vous','Je comprends que la sécurité passe d’abord. Cependant, je repars ce soir et je ne peux pas accepter ce report.','我理解安全优先。不过我今晚就离开，不能接受延期。'],
      ['Agent','Il existe aussi une visite du musée cet après-midi, au même prix. Est-ce que cela vous conviendrait ?','今天下午还有一次博物馆参观，价格相同。这样您方便吗？'],
      ['Vous','Ce serait possible à condition que la visite se termine avant seize heures. Mon train part à dix-sept heures et la gare est assez loin.','可以，前提是参观在四点前结束。我的火车五点开，而车站相当远。'],
      ['Agent','La visite finit à quinze heures trente. Je peux vous envoyer le programme et l’adresse du rendez-vous par courriel.','参观三点半结束。我可以把行程和集合地址发到您的邮箱。'],
      ['Vous','Merci. Avant de confirmer, pourriez-vous préciser si le transport jusqu’au musée est inclus ? Je voudrais éviter un autre imprévu.','谢谢。确认之前，您能说明去博物馆的交通是否包含在内吗？我想避免另一个意外。'],
    ],
    words:[['un report','n. m.','延期'],['un imprévu','n. m.','意外情况'],['à condition que','loc. conj.','条件是……']],
    grammar:{title:'à condition que + 虚拟式',explanation:'à condition que 引出必要条件，后面使用虚拟式。se terminer 与 la visite 连用时为 se termine。',example:'J’accepte à condition que le transport soit inclus.',translation:'我接受，条件是包含交通。',question:'补全：J’accepte à condition que le transport ___ inclus.',options:['sera','est','soit'],answer:2,why:'à condition que 后面用虚拟式；être 的相应形式为 soit。'},
    quiz:{question:'说话人为什么不能参加第二天的游览？',options:['今晚就要离开','不喜欢导游','博物馆太贵'],answer:0,why:'Je repars ce soir 是无法延期的实际原因。'},
    readingTask:{prompt:'说话人如何把情绪性投诉转为可以协商的问题？',answer:'先承认安全原因，再交代离程时间、参观结束时间和交通条件。每项要求都能由对方具体确认。'},
    writing:{prompt:'写 100–160 词给旅行机构：说明取消给你带来的问题，提出可接受的替代方案，并请求书面确认。',example:'Madame, Monsieur,\nMon excursion de ce matin a été annulée à cause de la météo. Je comprends cette décision, car la sécurité des participants est essentielle. Toutefois, le départ proposé demain ne me convient pas : je quitte la ville ce soir.\nVotre visite du musée pourrait constituer une solution, à condition qu’elle se termine avant seize heures. Mon train part à dix-sept heures et je dois prévoir le trajet jusqu’à la gare. Pourriez-vous également préciser si le transport vers le musée est compris dans le prix ?\nJe vous remercie de m’envoyer le programme, le lieu du rendez-vous et les éventuels frais supplémentaires avant ma confirmation. Ces informations me permettront de faire un choix sans risquer de manquer mon train.\nCordialement,',checklist:['我区分了事实、原因和自己的限制。','我请求确认的内容是具体且可回答的。']},
  },
  {
    topic:'home',title:'合租中的公平分工',fr:'Partager les tâches sans se disputer',goal:'解释分工问题，提出假设方案并讨论公平标准。',minutes:22,
    dialogue:[
      ['Colocataire','Tu dis que je ne fais pas assez de ménage, mais je sors les poubelles presque tous les jours.','你说我打扫得不够，但我几乎每天都倒垃圾。'],
      ['Vous','Je le reconnais. Ce qui me gêne, c’est que la cuisine reste souvent sale après le dîner et que je la nettoie seul.','这一点我承认。让我困扰的是晚饭后厨房常常很脏，而总是我一个人清理。'],
      ['Colocataire','Je rentre tard trois soirs par semaine. Un planning fixe ne serait pas très pratique pour moi.','我每周有三天很晚才回家。固定排班对我不太方便。'],
      ['Vous','Si nous répartissions les tâches sur toute la semaine, chacun pourrait choisir ses jours. Le but serait d’équilibrer le temps, pas de compter chaque geste.','如果把工作按整周分配，每个人就可以选自己的日子。目标是平衡时间，不是计较每一个动作。'],
      ['Colocataire','Je pourrais nettoyer la salle de bains le week-end et m’occuper de la cuisine le vendredi.','我可以周末打扫浴室，周五负责厨房。'],
      ['Vous','D’accord. Essayons pendant deux semaines, puis faisons le point. Si une tâche prend beaucoup plus de temps, nous adapterons la répartition.','好。试两周，再一起总结。如果某项工作耗时多很多，就调整分工。'],
    ],
    words:[['répartir','v.','分配'],['faire le point','expression','总结现状'],['équilibrer','v.','使平衡']],
    grammar:{title:'si + 未完成过去时，条件式现在时',explanation:'提出假设方案时，可以用 si + imparfait，主句用 conditionnel présent。si 从句里不用条件式。',example:'Si nous partagions mieux les tâches, nous aurions moins de disputes.',translation:'如果更好地分担家务，我们就会少些争吵。',question:'补全：Si nous ___ un planning, ce serait plus clair.',options:['ferions','faisions','ferons'],answer:1,why:'假设句的 si 从句用未完成过去时 faisions，主句用条件式。'},
    quiz:{question:'双方想用什么标准衡量公平？',options:['每个动作都一样多','谁先回家谁做全部家务','整体投入的时间是否平衡'],answer:2,why:'明确说到 équilibrer le temps，而不是 compter chaque geste。'},
    readingTask:{prompt:'“Je le reconnais”在争论中起什么作用？它是否等于接受现有分工？',answer:'它承认对方倒垃圾的贡献，降低对立；随后“Ce qui me gêne…”仍明确指出厨房清洁问题，因此不是接受现状。'},
    writing:{prompt:'给合租室友写 100–160 词的提议，先承认对方的贡献，再说明问题、分工方案和复盘时间。',example:'Salut Alex,\nMerci de sortir régulièrement les poubelles. Je sais aussi que tu rentres tard plusieurs soirs par semaine. Pourtant, notre organisation actuelle me pose problème, car je nettoie souvent la cuisine seul après le dîner.\nSi nous répartissions les tâches sur la semaine, chacun pourrait choisir les jours qui lui conviennent. Je ne souhaite pas compter chaque assiette lavée, mais équilibrer le temps consacré aux espaces communs. Tu pourrais prendre la salle de bains le week-end et la cuisine le vendredi. De mon côté, je m’occuperais des autres soirs et des sols.\nEssayons ce planning pendant deux semaines. Nous pourrons ensuite faire le point et modifier ce qui ne fonctionne pas. Qu’en penses-tu ?',checklist:['我承认了对方的贡献，没有只作指责。','我使用了一个正确的 si 假设句。']},
  },
  {
    topic:'work',title:'讨论远程办公',fr:'Travailler à distance, sous quelles conditions ?',goal:'平衡个人体验与团队需求，用让步结构提出有条件的立场。',minutes:24,
    dialogue:[
      ['Responsable','Plusieurs collègues souhaitent travailler à distance trois jours par semaine. D’autres craignent de perdre les échanges spontanés.','几位同事希望每周远程办公三天。另一些人担心失去自发交流。'],
      ['Vous','Bien que le travail à distance offre plus de souplesse, il ne règle pas tous les problèmes. Il faut distinguer les tâches individuelles des projets collectifs.','虽然远程办公更灵活，但不能解决所有问题。需要区分个人任务和集体项目。'],
      ['Responsable','Comment éviter que les personnes présentes au bureau reçoivent toutes les demandes urgentes ?','怎样避免所有紧急需求都落在到办公室的人身上？'],
      ['Vous','Nous pourrions désigner une personne disponible chaque jour, quel que soit son lieu de travail. Les demandes passeraient par un canal commun.','可以每天指定一位可联系的负责人，不论在哪里工作。所有需求都通过共同渠道提交。'],
      ['Responsable','Et pour accueillir les nouveaux collègues ? Un simple appel vidéo n’est pas toujours suffisant.','那新同事入职怎么办？一次视频通话不一定足够。'],
      ['Vous','Prévoyons des journées communes pour la formation et les décisions importantes. Après six semaines, nous comparerons la charge de travail et les difficultés rencontrées.','可以为培训和重要决策安排共同到岗日。六周后再比较工作负担和遇到的困难。'],
    ],
    words:[['la souplesse','n. f.','灵活性'],['une charge de travail','n. f.','工作负担'],['quel que soit','expression','无论……是什么']],
    grammar:{title:'bien que + 虚拟式表达让步',explanation:'bien que 引入被承认但不足以推翻主句的事实，后面通常使用虚拟式。',example:'Bien que cette formule soit souple, elle demande une organisation claire.',translation:'虽然这种方式灵活，但它需要明确的组织安排。',question:'补全：Bien que le dispositif ___ utile, il reste des difficultés.',options:['est','soit','sera'],answer:1,why:'bien que 后通常用虚拟式，因此选择 soit。'},
    quiz:{question:'怎样分配紧急请求？',options:['统一渠道，每天明确负责人','永远交给办公室的人','所有人同时处理'],answer:0,why:'建议设立 canal commun，并每天 désigner une personne disponible。'},
    readingTask:{prompt:'为什么把“远程办公好不好”改为“哪些任务适合远程”能推进讨论？',answer:'问题从笼统赞成或反对转为任务、责任和条件的安排，让培训、紧急请求等具体障碍可以分别解决。'},
    writing:{prompt:'写一份 100–160 词的团队建议：支持或反对部分远程办公，但必须回应协作和新人培训两项顾虑。',example:'Je suis favorable à deux journées de travail à distance par semaine, à condition que les responsabilités restent claires. Cette formule faciliterait les tâches qui demandent de la concentration et éviterait certains déplacements. Bien qu’elle offre davantage de souplesse, elle peut aussi rendre les échanges moins spontanés.\nPour préserver la coopération, je propose une journée commune au bureau et un canal unique pour les demandes urgentes. Une personne serait responsable de ce canal chaque jour, même si elle travaille chez elle. Les nouveaux collègues bénéficieraient de rencontres régulières avec un référent.\nEnfin, ce dispositif devrait être testé pendant six semaines. Nous évaluerions la charge de travail, les délais et les difficultés signalées, au lieu de juger uniquement le nombre de jours de présence.',checklist:['我回应了协作与培训两项顾虑。','我的让步结构后使用了恰当的动词形式。']},
  },
  {
    topic:'stories',title:'从一次失误中说明经验',fr:'Ce que cette erreur m’a appris',goal:'区分背景、先后事件与反思，避免把经历写成简单流水账。',minutes:22,
    dialogue:[
      ['Collègue','Tu as dit que ton premier atelier avait été difficile. Qu’est-ce qui s’est passé ?','你说第一次工作坊很困难。发生了什么？'],
      ['Vous','J’avais préparé beaucoup de diapositives, mais je n’avais pas demandé aux participants ce qu’ils connaissaient déjà.','我准备了很多幻灯片，却没有问参与者已经了解哪些内容。'],
      ['Collègue','Le niveau ne correspondait donc pas à leurs attentes ?','所以难度不符合他们的预期？'],
      ['Vous','Exactement. Pendant que j’expliquais les bases, plusieurs personnes s’ennuyaient. J’ai alors interrompu ma présentation pour leur proposer un exercice.','正是。我解释基础内容时，好几个人很无聊。于是我中断演示，给他们安排了练习。'],
      ['Collègue','Cela a suffi pour améliorer la séance ?','这样就足以改善课程了吗？'],
      ['Vous','Pas complètement, mais les échanges sont devenus plus riches. Depuis, j’envoie trois questions avant chaque atelier. Je garde aussi du temps pour adapter le programme.','不完全，但讨论变得更丰富。从那以后，每次工作坊前我都会发三个问题，也预留调整课程的时间。'],
    ],
    words:[['s’ennuyer','v. pron.','感到无聊'],['interrompre','v.','打断；中止'],['une attente','n. f.','期待']],
    grammar:{title:'愈过去时表示更早发生的事',explanation:'plus-que-parfait 用助动词的未完成过去时加过去分词构成，在过去的叙述中指更早的行动。',example:'J’avais préparé le cours avant de rencontrer le groupe.',translation:'见到这个小组前，我已经备好了课。',question:'哪一句明确说明“在那次活动开始前已经准备过”？',options:['Je préparerai l’atelier.','Je prépare l’atelier.','J’avais préparé l’atelier.'],answer:2,why:'avais préparé 是愈过去时，用于过去某时之前已经完成的准备。'},
    quiz:{question:'最初的问题出在哪里？',options:['没有任何课件','未了解参与者已有知识','参与者全部迟到'],answer:1,why:'说话人承认没有询问 ce qu’ils connaissaient déjà。'},
    readingTask:{prompt:'哪些行动是事前准备、现场调整和长期改变？',answer:'事前制作幻灯片但未调查；现场改为练习；之后固定发送问题并预留调整时间。三层时间共同构成反思。'},
    writing:{prompt:'写 100–160 词讲述一次学习或工作失误。说明先前准备、现场发生的事和你后来改变的做法；可使用虚构经历。',example:'Lors de mon premier atelier, j’avais préparé une présentation très détaillée. Je pensais que des explications complètes suffiraient à intéresser le groupe. Pourtant, je n’avais pas vérifié ce que les participants savaient déjà.\nAu début de la séance, plusieurs personnes regardaient leur téléphone pendant que je présentais les notions de base. J’ai compris que le programme était mal adapté. J’ai donc interrompu mon exposé et proposé un exercice en petits groupes. Les échanges sont devenus plus actifs, même si nous avons manqué de temps pour la conclusion.\nCette expérience m’a appris à préparer une séance avec les participants, et pas seulement pour eux. Désormais, je leur envoie quelques questions à l’avance et je garde une partie du programme flexible.',checklist:['我区分了背景、事件和更早的准备。','我说明了具体改变，而不只是说“学到了很多”。']},
  },
  {
    topic:'social',title:'协商一次集体活动',fr:'Choisir une sortie accessible à tous',goal:'总结不同人的限制，协商可执行的共同方案。',minutes:22,
    dialogue:[
      ['Amie','Pour notre sortie, certains proposent une randonnée, d’autres préfèrent un restaurant. Nous n’arrivons pas à nous décider.','这次出游有人提议徒步，有人更想去餐厅。我们一直定不下来。'],
      ['Vous','Avant de voter, vérifions les contraintes. Est-ce une question de budget, de transport ou de difficulté physique ?','投票前先看看限制条件。是预算、交通还是体力难度的问题？'],
      ['Amie','Deux personnes n’ont pas de voiture et une autre se remet d’une blessure. Le restaurant choisi est aussi assez cher.','两个人没有车，另一个人伤后还在恢复。选的餐厅也比较贵。'],
      ['Vous','Dans ce cas, un parc accessible en train conviendrait mieux. Nous pourrions prévoir une promenade courte et un pique-nique.','这样的话，坐火车可到的公园更合适。可以安排短距离散步和野餐。'],
      ['Amie','Et s’il pleut ? Nous risquons de devoir tout annuler au dernier moment.','如果下雨呢？可能要在最后一刻全部取消。'],
      ['Vous','Réservons une salle associative comme solution de repli, si elle est disponible. Ainsi, ceux qui ne peuvent pas marcher participeront aussi à la rencontre.','如果有空，就预订社区活动室作为备选。这样无法步行的人也能参加聚会。'],
    ],
    words:[['une contrainte','n. f.','限制条件'],['une solution de repli','n. f.','备选方案'],['au dernier moment','expression','在最后一刻']],
    grammar:{title:'ceux qui 指代某一类人',explanation:'ceux qui 表示“那些……的人”，后接描述他们的关系从句。阴性复数为 celles qui。',example:'Ceux qui ne peuvent pas marcher peuvent rester dans la salle.',translation:'无法步行的人可以留在活动室。',question:'补全：___ n’ont pas de voiture peuvent prendre le train.',options:['Ce qui','Ceux que','Ceux qui'],answer:2,why:'这里指人，且关系代词作 n’ont pas 的主语，所以用 ceux qui。'},
    quiz:{question:'为什么没有直接按多数票决定徒步？',options:['需要先考虑交通、预算和行动限制','所有人都不喜欢户外','公园已经关闭'],answer:0,why:'先核实 contraintes，能避免多数选择排除部分成员。'},
    readingTask:{prompt:'最终方案如何分别回应交通、体力、预算和天气问题？',answer:'乘火车到公园解决交通；短程散步与活动室照顾行动限制；野餐减少餐厅费用；室内备选应对雨天。'},
    writing:{prompt:'写 100–160 词的群组消息，提出兼顾不同限制的活动安排，并说明雨天备选。',example:'Bonjour à tous,\nAvant de choisir notre sortie, nous devons tenir compte des contraintes de chacun. Certains n’ont pas de voiture, tandis qu’une personne ne peut pas marcher longtemps. Le restaurant proposé dépasserait aussi le budget de plusieurs participants.\nJe suggère donc un pique-nique dans le parc près de la gare. Nous pourrions arriver en train vers midi, puis faire une promenade courte. Ceux qui préfèrent se reposer resteraient près de l’aire de pique-nique. Chacun apporterait un plat simple, ce qui limiterait les dépenses.\nEn cas de pluie, nous utiliserions la salle de l’association, si nous pouvons la réserver. Merci de confirmer votre disponibilité et de signaler vos besoins avant vendredi. Nous adapterons ensuite les derniers détails ensemble.',checklist:['我的方案没有忽略少数成员的实际限制。','消息包含确认安排与雨天备选。']},
  },
  {
    topic:'opinions',title:'转发前，先判断信息',fr:'Une information à vérifier',goal:'区分事实、推测与因果解释，提出核实信息的问题。',minutes:24,
    dialogue:[
      ['Ami','J’ai lu que les élèves qui utilisent cette application obtiennent de meilleures notes. Je vais partager l’article.','我读到使用这款应用的学生成绩更好。我想转发文章。'],
      ['Vous','Avant de le partager, regardons comment la comparaison a été faite. Les élèves avaient-ils le même niveau au départ ?','转发前先看看是怎么比较的。这些学生起点相同吗？'],
      ['Ami','L’article ne le précise pas. Il cite seulement le témoignage d’un professeur et un graphique sans source.','文章没有说。只引用了一位教师的证言和一张没有来源的图表。'],
      ['Vous','Le témoignage peut être intéressant, mais il ne prouve pas que l’application explique à elle seule les résultats. Les élèves les plus motivés l’utilisent peut-être davantage.','证言可能有价值，但不能证明成绩完全由应用造成。也许更积极的学生使用得更多。'],
      ['Ami','Donc, tu penses que l’article est faux ?','所以你认为文章是假的？'],
      ['Vous','Je dis plutôt que la conclusion est trop forte pour les éléments fournis. Cherchons la source du graphique et présentons cette limite si nous partageons le lien.','我的意思是，相对于提供的信息，结论太强。先找图表来源，如果转发，也说明这一限制。'],
    ],
    words:[['un témoignage','n. m.','证言；个人经历陈述'],['à elle seule','expression','仅凭它自身'],['un élément','n. m.','信息；依据']],
    grammar:{title:'用 peut-être 表示推测',explanation:'peut-être 可以标记尚未确认的解释。它与肯定事实不同，应结合来源和证据使用。',example:'Les élèves les plus motivés utilisent peut-être davantage l’application.',translation:'更积极的学生也许更经常使用这款应用。',question:'哪一句最准确地保留了不确定性？',options:['L’application explique forcément tous les résultats.','L’application contribue peut-être aux résultats.','Il est certain que le graphique est faux.'],answer:1,why:'peut-être 保留了可能性，没有把推测说成确定因果。'},
    quiz:{question:'说话人对文章的判断是什么？',options:['所有内容一定虚假','结论超出了已提供的依据','教师的意见永远不可信'],answer:1,why:'说话人明确说结论 trop forte，而不是直接认定文章虚假。'},
    readingTask:{prompt:'“依据不足”和“结论错误”有什么区别？用对话中的例子解释。',answer:'依据不足表示现有材料不能支持该强度的结论；它不直接证明相反结论为真。图表缺少来源，因此需核查，而不是立刻断言应用无效。'},
    writing:{prompt:'写 100–160 词回应一篇把学习进步归因于某工具的文章。区分观察、可能解释和仍需核实的问题。',example:'L’article affirme que cette application améliore les résultats scolaires. Il présente des élèves ayant obtenu de bonnes notes, mais ces observations ne suffisent pas à établir une relation de cause à effet. Nous ignorons leur niveau initial et le temps consacré aux révisions.\nIl est possible que l’application les ait aidés. Cependant, les élèves les plus motivés l’utilisent peut-être aussi plus régulièrement. Le témoignage d’un professeur apporte un point de vue utile, sans remplacer une comparaison détaillée.\nAvant de partager cet article, je chercherais donc la source du graphique et la méthode utilisée. Si ces informations restent introuvables, je présenterais le texte comme une piste à examiner, et non comme une preuve. Cette prudence ne signifie pas que l’application est inutile.',checklist:['我没有把缺少证据等同于结论必然错误。','我提出了至少两个具体的核实问题。']},
  },
]);
