import {createLessons} from './course-authoring';

export const a1Lessons=createLessons('A1',25,[
  {
    topic:'daily',title:'你好，我叫……',fr:'Bonjour, je m’appelle…',goal:'问候对方，用姓名、住处和职业介绍自己。',minutes:10,
    dialogue:[
      ['Léa','Bonjour ! Comment tu t’appelles ?','你好！你叫什么名字？'],
      ['Vous','Je m’appelle Lin. Et toi ?','我叫林。你呢？'],
      ['Léa','Moi, c’est Léa. Tu habites à Paris ?','我叫莱娅。你住在巴黎吗？'],
      ['Vous','Oui, j’habite à Paris. Je suis étudiante.','是的，我住在巴黎。我是女学生。'],
      ['Léa','Enchantée, Lin ! Moi, je suis professeure.','很高兴认识你，林！我是女教师。'],
      ['Vous','Enchantée ! À bientôt !','很高兴认识你！回头见！'],
    ],
    words:[['je m’appelle','expression','我叫……'],['habiter','v.','居住'],['enchanté / enchantée','adj.','很高兴认识你']],
    grammar:{title:'用 être 介绍身份',explanation:'je 对应 suis；tu 对应 es。说明职业或学生身份时，être 后通常直接接名词：Je suis étudiante。',example:'Je suis étudiante. Tu es professeur.',translation:'我是女学生。你是男教师。',question:'补全：Je ___ étudiante.',options:['es','suis','est'],answer:1,why:'être 与 je 连用时变为 suis。'},
    quiz:{question:'林住在哪里？',options:['里昂','巴黎','波尔多'],answer:1,why:'林说：j’habite à Paris。'},
    writing:{prompt:'写 20–40 个法语词介绍自己：姓名、居住城市、职业或学生身份。可以使用虚构信息。',example:'Bonjour ! Je m’appelle Mei. J’habite à Lyon. Je suis étudiante. J’aime le français et la musique. Et vous, comment vous appelez-vous ?'},
  },
  {
    topic:'food',title:'买一个面包',fr:'Une baguette, s’il vous plaît.',goal:'在面包店说出需要的商品和数量，听懂简单价格。',minutes:10,
    dialogue:[
      ['Boulanger','Bonjour ! Vous désirez ?','您好！您想要什么？'],
      ['Vous','Une baguette et deux croissants, s’il vous plaît.','请给我一根法棍和两个羊角面包。'],
      ['Boulanger','Voilà. Vous voulez un sac ?','给您。您要一个袋子吗？'],
      ['Vous','Oui, merci. C’est combien ?','好的，谢谢。多少钱？'],
      ['Boulanger','Quatre euros, s’il vous plaît.','请付四欧元。'],
      ['Vous','Voilà. Merci, au revoir !','给您。谢谢，再见！'],
    ],
    words:[['une baguette','n. f.','法棍面包'],['un sac','n. m.','袋子'],['c’est combien ?','expression','多少钱？']],
    grammar:{title:'un、une 与数量',explanation:'单个阳性名词前用 un，阴性名词前用 une。大于一的数量后通常使用复数：deux croissants。',example:'Une baguette et deux croissants.',translation:'一根法棍和两个羊角面包。',question:'补全：___ baguette, s’il vous plaît.',options:['Un','Une','Deux'],answer:1,why:'baguette 是阴性名词；单个法棍用 une baguette。'},
    quiz:{question:'你买了几个羊角面包？',options:['一个','三个','两个'],answer:2,why:'deux croissants 表示两个羊角面包。'},
    writing:{prompt:'写一段 20–40 词的购物小对话：问候、说出两种商品及数量、询问价格、道谢。',example:'Bonjour ! Je voudrais une baguette et deux croissants, s’il vous plaît. C’est combien ? Quatre euros ? D’accord. Je voudrais aussi un sac. Merci beaucoup, au revoir !'},
  },
  {
    topic:'travel',title:'车站在哪里？',fr:'Où est la gare ?',goal:'问路，听懂直走、左转和地标位置。',minutes:12,
    dialogue:[
      ['Passant','Bonjour, vous cherchez quelque chose ?','您好，您在找什么吗？'],
      ['Vous','Oui, où est la gare, s’il vous plaît ?','是的，请问车站在哪里？'],
      ['Passant','Allez tout droit, puis à gauche.','直走，然后向左。'],
      ['Vous','À gauche, après la pharmacie ?','过了药店向左吗？'],
      ['Passant','Oui. La gare est en face du café.','对。车站就在咖啡馆对面。'],
      ['Vous','D’accord, merci beaucoup !','好的，非常感谢！'],
    ],
    words:[['tout droit','loc. adv.','一直往前'],['à gauche','loc. adv.','向左；在左边'],['en face de','loc. prép.','在……对面']],
    grammar:{title:'Où est… ? 询问地点',explanation:'où 表示“哪里”，带重音符号。询问一个地点用 Où est… ?；问多个地点用 Où sont… ?。',example:'Où est la gare ? Elle est en face du café.',translation:'车站在哪里？它在咖啡馆对面。',question:'你想问“车站在哪里？”，选择正确句子。',options:['Quand est la gare ?','Qui est la gare ?','Où est la gare ?'],answer:2,why:'où 用于询问地点；quand 问时间，qui 问人。'},
    quiz:{question:'车站在什么地方？',options:['咖啡馆对面','药店里面','咖啡馆后面'],answer:0,why:'La gare est en face du café，表示车站在咖啡馆对面。'},
    writing:{prompt:'写 20–40 词告诉朋友怎样从这里走到车站：使用 tout droit、à gauche 和一个地标。',example:'Salut ! Pour aller à la gare, va tout droit, puis à gauche après la pharmacie. La gare est en face du café. À bientôt !'},
  },
  {
    topic:'home',title:'介绍我的房间',fr:'Dans ma chambre',goal:'用 il y a 描述房间里的物品和简单位置。',minutes:10,
    dialogue:[
      ['Ami','Ta chambre est grande ?','你的房间大吗？'],
      ['Vous','Non, elle est petite, mais elle est claire.','不大，房间很小，但是很明亮。'],
      ['Ami','Il y a un bureau ?','有书桌吗？'],
      ['Vous','Oui, il y a un bureau près de la fenêtre.','有，窗户旁边有一张书桌。'],
      ['Ami','Et tes livres, ils sont où ?','那你的书在哪里？'],
      ['Vous','Ils sont sur le bureau, à côté de la lampe.','在书桌上，台灯旁边。'],
    ],
    words:[['il y a','expression','有'],['une fenêtre','n. f.','窗户'],['à côté de','loc. prép.','在……旁边']],
    grammar:{title:'用 il y a 表示“有”',explanation:'il y a 可以接单数或复数名词，形式不变。描述物品位置可用 sur（在……上）和 près de（在……附近）。',example:'Il y a deux livres sur le bureau.',translation:'书桌上有两本书。',question:'补全：Dans ma chambre, ___ un bureau.',options:['il y a','je suis','elle habite'],answer:0,why:'表示房间里存在某件物品，用 il y a。'},
    quiz:{question:'书在哪里？',options:['床下面','书桌上','窗户外面'],answer:1,why:'Ils sont sur le bureau 指书在书桌上。'},
    writing:{prompt:'用 20–40 词描述一个房间，写出三件物品和至少一个位置。',example:'Ma chambre est petite et claire. Il y a un lit, un bureau et une lampe. Le bureau est près de la fenêtre. Mes livres sont sur le bureau.'},
  },
  {
    topic:'work',title:'我的一周课程',fr:'Le cours commence à neuf heures.',goal:'询问上课的日期、时间和地点。',minutes:12,
    dialogue:[
      ['Secrétaire','Bonjour ! Vous êtes dans le cours de français ?','您好！您是法语班的学生吗？'],
      ['Vous','Oui. Le cours est quel jour ?','是的。课程是星期几？'],
      ['Secrétaire','Le lundi et le mercredi, à neuf heures.','星期一和星期三，九点。'],
      ['Vous','Et c’est dans quelle salle ?','在哪个教室？'],
      ['Secrétaire','Dans la salle douze. Le cours finit à onze heures.','在十二号教室。课程十一点结束。'],
      ['Vous','Merci. À lundi !','谢谢。星期一见！'],
    ],
    words:[['le lundi','expression','每周一'],['une salle','n. f.','房间；教室'],['à neuf heures','expression','在九点']],
    grammar:{title:'日期与时刻',explanation:'星期前加 le 可以表示每周重复的安排：le lundi。时间点前用 à：à neuf heures。',example:'J’ai cours le lundi à neuf heures.',translation:'我每周一九点有课。',question:'补全：Le cours commence ___ neuf heures.',options:['de','à','en'],answer:1,why:'具体时刻之前使用 à。'},
    quiz:{question:'课程几点结束？',options:['九点','十二点','十一点'],answer:2,why:'Le cours finit à onze heures，十一点结束。'},
    writing:{prompt:'写 20–40 词告诉朋友你的上课安排：星期、开始时间、结束时间和教室。',example:'Bonjour ! J’ai un cours de français le lundi et le mercredi. Il commence à neuf heures et finit à onze heures. Nous sommes dans la salle douze.'},
  },
  {
    topic:'stories',title:'我平常的一天',fr:'Une journée simple',goal:'用现在时按顺序说出一天的日常活动。',minutes:12,
    dialogue:[
      ['Ami','Tu commences ta journée à quelle heure ?','你的一天几点开始？'],
      ['Vous','À sept heures. Je prends un café à la maison.','七点。我在家喝一杯咖啡。'],
      ['Ami','Et ensuite ?','然后呢？'],
      ['Vous','Ensuite, je marche jusqu’à l’école. Le cours commence à neuf heures.','然后我步行去学校。课程九点开始。'],
      ['Ami','Tu regardes la télévision le soir ?','你晚上看电视吗？'],
      ['Vous','Non, je lis un livre. Puis, je dors.','不，我读一本书。之后就睡觉。'],
    ],
    words:[['ensuite','adv.','然后'],['marcher','v.','步行'],['le soir','expression','在晚上']],
    grammar:{title:'现在时描述习惯',explanation:'日常习惯通常用现在时。以 -er 结尾的规则动词与 je 连用，词尾为 -e：je marche，je regarde。',example:'Je marche jusqu’à l’école. Ensuite, je travaille.',translation:'我步行去学校。然后我学习或工作。',question:'补全：Le matin, je ___ jusqu’à l’école.',options:['marches','marchent','marche'],answer:2,why:'主语是 je，marcher 的现在时形式是 marche。'},
    quiz:{question:'晚上你通常做什么？',options:['看书','看电视','去学校'],answer:0,why:'回答是 je lis un livre，并明确表示不看电视。'},
    writing:{prompt:'用 20–40 词介绍平常的一天。用现在时，加入 le matin、ensuite 或 le soir。',example:'Le matin, je prends un café à sept heures. Ensuite, je marche jusqu’à l’école. Le soir, je mange à la maison et je lis un livre.'},
  },
  {
    topic:'social',title:'周六一起见面',fr:'On se retrouve samedi ?',goal:'提出简单邀请，确认时间和地点。',minutes:10,
    dialogue:[
      ['Ami','Tu es libre samedi ?','你周六有空吗？'],
      ['Vous','Oui ! Tu veux aller au parc ?','有！你想去公园吗？'],
      ['Ami','Bonne idée ! À quelle heure ?','好主意！几点？'],
      ['Vous','À trois heures, devant le café du parc.','三点，在公园咖啡馆前面。'],
      ['Ami','D’accord. Avec Julie ?','好的。和朱莉一起吗？'],
      ['Vous','Oui, avec Julie. À samedi !','是的，和朱莉一起。周六见！'],
    ],
    words:[['être libre','expression','有空'],['devant','prép.','在……前面'],['avec','prép.','和……一起']],
    grammar:{title:'tu 和 vous',explanation:'熟悉的人之间可用 tu；对不熟悉的成年人或多人用 vous。本课朋友间的提问为 Tu es libre ?。',example:'Tu es libre samedi ? Vous êtes libre samedi ?',translation:'你周六有空吗？您周六有空吗？',question:'和一位朋友聊天，补全：Tu ___ libre samedi ?',options:['es','suis','êtes'],answer:0,why:'être 与 tu 连用时变为 es。'},
    quiz:{question:'大家在哪里见面？',options:['朱莉家里','学校门口','公园咖啡馆前面'],answer:2,why:'devant le café du parc 表示在公园咖啡馆前面。'},
    writing:{prompt:'给朋友写一条 20–40 词的邀请消息，说明星期、时间、地点和活动。',example:'Salut Julie ! Tu es libre samedi ? On va au parc ensemble ? Rendez-vous à trois heures devant le café du parc. Lin vient aussi. À samedi !'},
  },
  {
    topic:'opinions',title:'说说你喜欢什么',fr:'J’aime la musique.',goal:'用 aimer 和 ne… pas 表达简单喜好。',minutes:10,
    dialogue:[
      ['Ami','Tu aimes la musique ?','你喜欢音乐吗？'],
      ['Vous','Oui, j’aime le jazz. Et toi ?','喜欢，我喜欢爵士乐。你呢？'],
      ['Ami','Moi, j’aime le rock. Tu aimes aussi le sport ?','我喜欢摇滚乐。你也喜欢运动吗？'],
      ['Vous','J’aime le tennis, mais je n’aime pas le football.','我喜欢网球，但是不喜欢足球。'],
      ['Ami','Tu joues au tennis le dimanche ?','你星期天打网球吗？'],
      ['Vous','Oui, avec mon frère. C’est sympa !','对，和我的兄弟一起。很不错！'],
    ],
    words:[['aimer','v.','喜欢'],['mais','conj.','但是'],['sympa','adj. familier','不错的；友好的']],
    grammar:{title:'ne… pas 表示否定',explanation:'一般把 ne 和 pas 放在变位动词两侧。动词以元音开头时，ne 变成 n’：je n’aime pas。',example:'J’aime le tennis, mais je n’aime pas le football.',translation:'我喜欢网球，但不喜欢足球。',question:'“我不喜欢足球”应该怎么说？',options:['Je pas aime le football.','Je n’aime pas le football.','Je ne pas aime le football.'],answer:1,why:'n’ 在 aime 前，pas 在 aime 后。'},
    quiz:{question:'你不喜欢哪项运动？',options:['足球','网球','对话没有说'],answer:0,why:'Je n’aime pas le football，明确表示不喜欢足球。'},
    writing:{prompt:'写 20–40 词介绍两种喜好和一种不喜欢的活动，使用 mais 或 et 连接句子。',example:'J’aime la musique et le tennis. Le dimanche, je joue au tennis avec mon frère. Je n’aime pas le football, mais j’aime regarder un film le soir.'},
  },
]);
